project:
  type: book
  output-dir: docs

book:
  title: "COMP/STAT112 Notebook"
  author: "Zhijun He"
  date: today
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  
  
  sidebar:
    title: "Zhijun He"
    collapse-level: 2
    style: "docked"
    pinned: true
    search: true
  
  
  chapters:
    - index.qmd

    - part: "Best Work"
      chapters: 
      - bw/bw-uni.qmd
      - bw/bw-bi.qmd
      - bw/bw-tri.qmd
      - bw/bw-quad.qmd
      - bw/bw-spatial.qmd
      - bw/Zhijun He-Exam1.qmd
      - bw/Zhijun He-Exam2.qmd
      

    - part: "In-class Activities"
      chapters: 
      - ica/ica-uni.qmd
      - ica/ica-bi.qmd
      - ica/ica-multi.qmd
      - ica/real-ica-spacial.qmd
      - ica/ica-effective viz.qmd
      - ica/ica-data wrangling.qmd
      - ica/ica-working with dates.qmd
      - ica/ica-reshaping data.qmd
      - ica/ica-joining data.qmd
      - ica/ica-working with factors.qmd
      - ica/ica-working with strings.qmd
      - ica/ica-working with data import.qmd
      - ica/ica-EDA.qmd
      

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    css: style/custom.css
    code-copy: true
    code-link: true
    code-line-numbers: true
    code-tools: true

execute:
  cache: false
  freeze: false

editor: 
  markdown:
    wrap: sentence # Forces each sentence to be on its own line in source markdown, however, it doesn't affect how it is rendered
