<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>20&nbsp; Data Import – COMP/STAT112 Notebook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../ica/ica-EDA.html" rel="next">
<link href="../ica/ica-working with strings.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link rel="stylesheet" href="../style/custom.css">
</head>
<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../ica/ica-uni.html">In-class Activities</a></li><li class="breadcrumb-item"><a href="../ica/ica-working with data import.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Data Import</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Zhijun He</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Best Work</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/bw-uni.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Univariate Visualization-Best Work</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/bw-bi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bivariate Visualization-Best Work</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/bw-tri.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Trivariate Visualization-Best Work</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/bw-quad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Quadvariate Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/bw-spatial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Spatial Viz-Best Work</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/Zhijun He-Exam1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Exam 1:Food Consumption and CO2 Emissions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/Zhijun He-Exam2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Food Consumption-Zhijun's Exam 2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bw/Solo Project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Australia Fires: A Spatial and Temporal Analysis</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">In-class Activities</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-uni.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Univariate Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-bi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Bivariate Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-multi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Multivariate Viz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/real-ica-spacial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Spatial Visualization Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-effective viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Effective Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-data wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-working with dates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Working with Dates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-reshaping data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Reshaping Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-joining data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Joining Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-working with factors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Working with Factors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-working with strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Working with Strings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-working with data import.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Data Import</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ica/ica-EDA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#learning-goals" id="toc-learning-goals" class="nav-link active" data-scroll-target="#learning-goals"><span class="header-section-number">20.1</span> Learning Goals</a></li>
  <li><a href="#additional-resources" id="toc-additional-resources" class="nav-link" data-scroll-target="#additional-resources"><span class="header-section-number">20.2</span> Additional Resources</a></li>
  <li><a href="#review" id="toc-review" class="nav-link" data-scroll-target="#review"><span class="header-section-number">20.3</span> 14.1 Review</a></li>
  <li>
<a href="#data-import" id="toc-data-import" class="nav-link" data-scroll-target="#data-import"><span class="header-section-number">20.4</span> 14.2 Data Import</a>
  <ul class="collapse">
<li><a href="#starting-data-project" id="toc-starting-data-project" class="nav-link" data-scroll-target="#starting-data-project"><span class="header-section-number">20.4.1</span> Starting Data Project</a></li>
  <li><a href="#file-formats" id="toc-file-formats" class="nav-link" data-scroll-target="#file-formats"><span class="header-section-number">20.4.2</span> File Formats</a></li>
  <li><a href="#step-1-find-data" id="toc-step-1-find-data" class="nav-link" data-scroll-target="#step-1-find-data"><span class="header-section-number">20.4.3</span> STEP 1: Find Data</a></li>
  <li><a href="#step-2-save-data-locally" id="toc-step-2-save-data-locally" class="nav-link" data-scroll-target="#step-2-save-data-locally"><span class="header-section-number">20.4.4</span> STEP 2: Save Data Locally</a></li>
  <li><a href="#step-3-import-data-to-rstudio" id="toc-step-3-import-data-to-rstudio" class="nav-link" data-scroll-target="#step-3-import-data-to-rstudio"><span class="header-section-number">20.4.5</span> STEP 3: Import Data to RStudio</a></li>
  <li><a href="#step-4-check-clean-data" id="toc-step-4-check-clean-data" class="nav-link" data-scroll-target="#step-4-check-clean-data"><span class="header-section-number">20.4.6</span> STEP 4: Check &amp; Clean Data</a></li>
  <li><a href="#step-5-understand-data" id="toc-step-5-understand-data" class="nav-link" data-scroll-target="#step-5-understand-data"><span class="header-section-number">20.4.7</span> STEP 5: Understand Data</a></li>
  </ul>
</li>
  <li>
<a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">20.5</span> 14.3 Exercises</a>
  <ul class="collapse">
<li><a href="#exercise-1-save-data-locally" id="toc-exercise-1-save-data-locally" class="nav-link" data-scroll-target="#exercise-1-save-data-locally"><span class="header-section-number">20.5.1</span> Exercise 1: Save Data Locally</a></li>
  <li><a href="#exercise-2-import-data-to-rstudio" id="toc-exercise-2-import-data-to-rstudio" class="nav-link" data-scroll-target="#exercise-2-import-data-to-rstudio"><span class="header-section-number">20.5.2</span> Exercise 2: Import Data to RStudio</a></li>
  <li><a href="#exercise-3-check-data" id="toc-exercise-3-check-data" class="nav-link" data-scroll-target="#exercise-3-check-data"><span class="header-section-number">20.5.3</span> Exercise 3: Check Data</a></li>
  <li><a href="#exercise-4-clean-data-factor-variables-1" id="toc-exercise-4-clean-data-factor-variables-1" class="nav-link" data-scroll-target="#exercise-4-clean-data-factor-variables-1"><span class="header-section-number">20.5.4</span> Exercise 4: Clean Data: Factor Variables 1</a></li>
  <li><a href="#exercise-5-clean-data-factor-variables-2" id="toc-exercise-5-clean-data-factor-variables-2" class="nav-link" data-scroll-target="#exercise-5-clean-data-factor-variables-2"><span class="header-section-number">20.5.5</span> Exercise 5: Clean Data: Factor Variables 2</a></li>
  <li><a href="#exercise-6-clean-data-missing-data-1" id="toc-exercise-6-clean-data-missing-data-1" class="nav-link" data-scroll-target="#exercise-6-clean-data-missing-data-1"><span class="header-section-number">20.5.6</span> Exercise 6: Clean Data: Missing Data 1</a></li>
  <li><a href="#exercise-7-clean-data-missing-data-2" id="toc-exercise-7-clean-data-missing-data-2" class="nav-link" data-scroll-target="#exercise-7-clean-data-missing-data-2"><span class="header-section-number">20.5.7</span> Exercise 7: Clean Data: Missing Data 2</a></li>
  <li><a href="#exercise-8-new-data-projects" id="toc-exercise-8-new-data-projects" class="nav-link" data-scroll-target="#exercise-8-new-data-projects"><span class="header-section-number">20.5.8</span> Exercise 8: New Data + Projects</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../ica/ica-uni.html">In-class Activities</a></li><li class="breadcrumb-item"><a href="../ica/ica-working with data import.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Data Import</span></a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Data Import</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="learning-goals" class="level2" data-number="20.1"><h2 data-number="20.1" class="anchored" data-anchor-id="learning-goals">
<span class="header-section-number">20.1</span> Learning Goals</h2>
<p>Get a glimpse into how to…</p>
<ul>
<li>find existing data sets</li>
<li>save data sets locally</li>
<li>load data into RStudio</li>
<li>do some preliminary data checking and cleaning steps before further wrangling / visualization:
<ul>
<li>make sure variables are properly formatted</li>
<li>deal with missing values</li>
</ul>
</li>
</ul>
<p>NOTE: These skills are best learned through practice. We’ll just scratch the surface here.</p>
</section><section id="additional-resources" class="level2" data-number="20.2"><h2 data-number="20.2" class="anchored" data-anchor-id="additional-resources">
<span class="header-section-number">20.2</span> Additional Resources</h2>
<p>For more information about the topics covered in this chapter, refer to the resources below:</p>
<ul>
<li>
<a href="https://www.youtube.com/watch?v=EWz9siRXLdM">Using the import wizard (YouTube)</a> by Lisa Lendway</li>
<li><a href="https://posit.co/wp-content/uploads/2022/10/data-import-cheatsheet.pdf">data import cheat sheet (pdf)</a></li>
<li><a href="https://readr.tidyverse.org/">readr documentation (html)</a></li>
<li>
<a href="https://r4ds.had.co.nz/data-import.html">Data import (html)</a> by Wickham and Grolemund</li>
<li>
<a href="https://r4ds.had.co.nz/tidy-data.html#missing-values-3">Missing data (html)</a> by Wickham and Grolemund</li>
<li>
<a href="https://mdsr-book.github.io/mdsr2e/ch-dataI.html">Data intake (html)</a> by Baumer, Kaplan, and Horton</li>
</ul></section><section id="review" class="level2" data-number="20.3"><h2 data-number="20.3" class="anchored" data-anchor-id="review">
<span class="header-section-number">20.3</span> 14.1 Review</h2>
<p>WHERE ARE WE?</p>
<p>We’ve thus far focused on data preparation and visualization:</p>
<p>What’s coming up?</p>
<p>In the last few weeks we’ll focus on data storytelling through the completion of a course project.</p>
<p>This week we’ll address the other gaps in the workflow: data collection and analysis. We’ll do so in the context of starting a data project…</p>
</section><section id="data-import" class="level2" data-number="20.4"><h2 data-number="20.4" class="anchored" data-anchor-id="data-import">
<span class="header-section-number">20.4</span> 14.2 Data Import</h2>
<section id="starting-data-project" class="level3" data-number="20.4.1"><h3 data-number="20.4.1" class="anchored" data-anchor-id="starting-data-project">
<span class="header-section-number">20.4.1</span> Starting Data Project</h3>
<p>Any data science project consists of two phases:</p>
<ol type="1">
<li>
<strong>Data Collection</strong> A data project starts with data! Thus far, you’ve either been given data, or used TidyTuesday data. In this unit:
<ul>
<li>We WILL explore how to find data, save data, import this data into RStudio, and do some preliminary data cleaning.</li>
<li>We will NOT discuss how to collect data from scratch (e.g.&nbsp;via experiment, observational study, or survey).</li>
</ul>
</li>
<li>
<strong>Data Analysis</strong> Once we have data, we need to do some analysis. In this unit…
<ul>
<li>We WILL bring together our wrangling &amp; visualization tools to discuss exploratory data analysis (EDA). EDA is the process of getting to know our data, obtaining insights from data, and using these insights to formulate, refine, and explore research questions.</li>
<li>We will NOT explore other types of analysis, such as modeling &amp; prediction–if interested, take STAT 155 and 253 to learn more about these topics.</li>
</ul>
</li>
</ol>
<p>NOTE: These skills are best learned through practice. We’ll just scratch the surface here.</p>
</section><section id="file-formats" class="level3" data-number="20.4.2"><h3 data-number="20.4.2" class="anchored" data-anchor-id="file-formats">
<span class="header-section-number">20.4.2</span> File Formats</h3>
<p>Before exploring how to find, store, import, check, and clean data, it’s important to recognize that data can be stored in various formats. We’ve been working with .csv files. In the background, these have “comma-separated values” (csv):</p>
<p>But there are many other common file types. For example, the following are compatible with R:</p>
<ul>
<li>Excel files: .xls, .xlsx</li>
<li>R “data serialization” files: .rds</li>
<li>files with tab-separated values: .tsv</li>
</ul></section><section id="step-1-find-data" class="level3" data-number="20.4.3"><h3 data-number="20.4.3" class="anchored" data-anchor-id="step-1-find-data">
<span class="header-section-number">20.4.3</span> STEP 1: Find Data</h3>
<p>Check the Datasets page for information about how to find a dataset that fits your needs.</p>
</section><section id="step-2-save-data-locally" class="level3" data-number="20.4.4"><h3 data-number="20.4.4" class="anchored" data-anchor-id="step-2-save-data-locally">
<span class="header-section-number">20.4.4</span> STEP 2: Save Data Locally</h3>
<p>Unless we’re just doing a quick, one-off data analysis, it’s important to store a local copy of a data file, i.e.&nbsp;save the data file to our own machine.</p>
<p>Mainly, we shouldn’t rely on another person / institution to store a data file online, in the same place, forever!</p>
<section id="recommendations-when-saving-data" class="level4" data-number="20.4.4.1"><h4 data-number="20.4.4.1" class="anchored" data-anchor-id="recommendations-when-saving-data">
<span class="header-section-number">20.4.4.1</span> Recommendations when Saving Data</h4>
<p>When saving your data, make sure they are: - in a nice format, eg, a csv file format - where you’ll be able to find it again - ideally, within a folder that’s dedicated to the related project / assignment - alongside the qmd file(s) where you’ll record your analysis of the data</p>
</section></section><section id="step-3-import-data-to-rstudio" class="level3" data-number="20.4.5"><h3 data-number="20.4.5" class="anchored" data-anchor-id="step-3-import-data-to-rstudio">
<span class="header-section-number">20.4.5</span> STEP 3: Import Data to RStudio</h3>
<p>Once we have a local copy of our data file, we need to get it into RStudio! This process depends on 2 things: (1) the file type (e.g.&nbsp;.csv); and (2) the file location, i.e.&nbsp;where it’s stored on your computer.</p>
<section id="file-type" class="level4" data-number="20.4.5.1"><h4 data-number="20.4.5.1" class="anchored" data-anchor-id="file-type">
<span class="header-section-number">20.4.5.1</span> 1. FILE TYPE</h4>
<p>The file type indicates which function we’ll need to import it. The table below lists some common import functions and when to use them.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 80%">
</colgroup>
<thead><tr class="header">
<th>Function</th>
<th>Data file type</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>read_csv()</td>
<td>.csv - you can save Excel files and Google Sheets as .csv</td>
</tr>
<tr class="even">
<td>read_delim()</td>
<td>other delimited formats (tab, space, etc.)</td>
</tr>
<tr class="odd">
<td>read_sheet()</td>
<td>Google Sheet</td>
</tr>
<tr class="even">
<td>st_read()</td>
<td>spatial data shapefile</td>
</tr>
</tbody>
</table>
<p>NOTE: In comparison to read.csv, read_csv is faster when importing large data files and can more easily parse complicated datasets, eg, with dates, times, percentages.</p>
</section><section id="file-location" class="level4" data-number="20.4.5.2"><h4 data-number="20.4.5.2" class="anchored" data-anchor-id="file-location">
<span class="header-section-number">20.4.5.2</span> 2. FILE LOCATION</h4>
<p>To import the data, we apply the appropriate function from above to the file path.</p>
<p>A file path is an address to where the file is stored on our computer or the web.</p>
<p>Consider “1600 Grand Ave, St.&nbsp;Paul, MN 55105”. Think about how different parts of the address give increasingly more specific information about the location. “St.&nbsp;Paul, MN 55105” tells us the city and smaller region within the city, “Grand Ave” tells us the street, and “1600” tells us the specific location on the street.</p>
<p>In the example below, the file path is absolute where it tells us the location giving more and more specific information as you read it from left to right.</p>
<ul>
<li>“~”, on an Apple computer, tells you that you are looking in the user’s home directory.</li>
<li>“Desktop” tells you to go to the Desktop within that home directory.</li>
<li>“112” tells you that you are looking in the 112 folder on the Desktop.</li>
<li>“data” tells you to next go in the data folder in the 112 folder.</li>
<li>“my_data.csv” tells you that you are looking for a file called my_data.csv location within the data folder.</li>
</ul>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2"></a>my_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"~/Desktop/112/data/my_data.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Absolute file paths should only be used when reading files hosted on the web. Otherwise, relative file paths should be used. Relative file paths as the name suggest is relative to the file where the data file is read.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># assume the code containing this script is under a folder called /src which</span></span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="co"># is at the same level of the /data folder</span></span>
<span id="cb2-3"><a href="#cb2-3"></a></span>
<span id="cb2-4"><a href="#cb2-4"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-5"><a href="#cb2-5"></a>my_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../data/my_data.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section></section><section id="step-4-check-clean-data" class="level3" data-number="20.4.6"><h3 data-number="20.4.6" class="anchored" data-anchor-id="step-4-check-clean-data">
<span class="header-section-number">20.4.6</span> STEP 4: Check &amp; Clean Data</h3>
<p>Once the data is loaded, ask yourself a few questions:</p>
<ol type="1">
<li>What’s the structure of the data?
<ul>
<li>Use str() to learn about the numbers of variables and observations as well as the classes or types of variables (date, location, string, factor, number, boolean, etc.)</li>
<li>Use head() to view the top of the data table</li>
<li>Use View() to view the data in a spreadsheet-like viewer, use this command in the Console but don’t include it in your qmd files since it will prevent your project from rendering.</li>
</ul>
</li>
<li>Is there anything goofy that we need to clean before we can analyze the data?
<ul>
<li>Is it in a tidy format?</li>
<li>How many rows are there? What does the row mean? What is an observation?</li>
<li>Is there consistent formatting for categorical variables?</li>
<li>Is there missing data that needs to be addressed?</li>
</ul>
</li>
</ol></section><section id="step-5-understand-data" class="level3" data-number="20.4.7"><h3 data-number="20.4.7" class="anchored" data-anchor-id="step-5-understand-data">
<span class="header-section-number">20.4.7</span> STEP 5: Understand Data</h3>
<p>Start by understanding the data that is available to you. If you have a codebook, you have struck gold! If not (the more common case), you’ll need to do some detective work that often involves talking to people.</p>
<p>At this stage, ask yourself: - Where does my data come from? How was it collected? - Is there a codebook? If not, how can I learn more about it? - Are there people I can reach out to who have experience with this data?</p>
</section></section><section id="exercises" class="level2" data-number="20.5"><h2 data-number="20.5" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">20.5</span> 14.3 Exercises</h2>
<p>Suppose our goal is to work with data on movie reviews, and that we’ve already gone through the work to find a dataset. The imdb_5000_messy.csv file is posted on Moodle. Let’s work with it!</p>
<section id="exercise-1-save-data-locally" class="level3" data-number="20.5.1"><h3 data-number="20.5.1" class="anchored" data-anchor-id="exercise-1-save-data-locally">
<span class="header-section-number">20.5.1</span> Exercise 1: Save Data Locally</h3>
<section id="part-a" class="level4" data-number="20.5.1.1"><h4 data-number="20.5.1.1" class="anchored" data-anchor-id="part-a">
<span class="header-section-number">20.5.1.1</span> Part a</h4>
<p>On your laptop: - Download the “imdb_5000_messy.csv” file from Moodle - Move it to the data folder in your portfolio repository</p>
</section><section id="part-b" class="level4" data-number="20.5.1.2"><h4 data-number="20.5.1.2" class="anchored" data-anchor-id="part-b">
<span class="header-section-number">20.5.1.2</span> Part b</h4>
<p>Hot tip: After saving your data file, it’s important to record appropriate citations and info in either a new qmd (eg: “imdb_5000_messy_README.qmd”) or in the qmd where you’ll analyze the data. These citations should include:</p>
<ul>
<li>the data source, i.e.&nbsp;where you found the data</li>
<li>the data creator, i.e.&nbsp;who / what group collected the original data</li>
<li>possibly a data codebook, i.e.&nbsp;descriptions of the data variables</li>
</ul>
<p>To this end, check out where we originally got our IMDB data: <a href="https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata" class="uri">https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata</a></p>
<p>After visiting that website, take some quick notes here on the data source and creator:</p>
<p><em>The data comes from Kaggle, a platform for data science competitions and datasets. The dataset was created by TMDB (The Movie Database), which is a community-built movie and TV database. The dataset contains information about 5,000 movies from IMDB, including details about cast, directors, ratings, revenue, and Facebook likes for various individuals involved in the films.</em></p>
</section></section><section id="exercise-2-import-data-to-rstudio" class="level3" data-number="20.5.2"><h3 data-number="20.5.2" class="anchored" data-anchor-id="exercise-2-import-data-to-rstudio">
<span class="header-section-number">20.5.2</span> Exercise 2: Import Data to RStudio</h3>
<p>Now that we have a local copy of our data file, let’s get it into RStudio! Remember that this process depends on 2 things: the file type and location. Since our file type is a csv, we can import it using read_csv(). But we have to supply the file location through a file path. To this end, we can either use an absolute file path or a relative file path.</p>
<section id="part-a-1" class="level4" data-number="20.5.2.1"><h4 data-number="20.5.2.1" class="anchored" data-anchor-id="part-a-1">
<span class="header-section-number">20.5.2.1</span> Part a</h4>
<p>An absolute file path describes the location of a file starting from the root or home directory. How we refer to the user root directory depends upon your machine:</p>
<ul>
<li>On a Mac: ~</li>
<li>On Windows: typically C:<br>
</li>
</ul>
<p>Then the complete file path to the IMDB data file in the data folder, depending on your machine an where you created your portfolio project, can be:</p>
<ul>
<li>On a Mac: ~/Desktop/portfolio/data/imdb_5000_messy.csv</li>
<li>On Windows: C:_5000_messy.csv or C:\Desktop\portfolio\data\imdb_5000_messy.csv</li>
</ul>
<p>Putting this together, use read_csv() with the appropriate absolute file path to import your data into RStudio. Save this as imdb_messy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># Using a placeholder path - you will need to use your actual path</span></span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="co"># imdb_messy &lt;- read_csv("~/Desktop/portfolio/data/imdb_5000_messy.csv")</span></span>
<span id="cb5-3"><a href="#cb5-3"></a></span>
<span id="cb5-4"><a href="#cb5-4"></a><span class="co"># For this activity, let's load from an online source so the code runs for everyone</span></span>
<span id="cb5-5"><a href="#cb5-5"></a>imdb_messy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://mac-stat.github.io/data/imdb_5000_messy.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
Rows: 5043 Columns: 29
── Column specification
──────────────────────────────────────────────────────── Delimiter: "," chr
(12): color, director_name, actor_2_name, genres, actor_1_name, movie_ti... dbl
(17): ...1, num_critic_for_reviews, duration, director_facebook_likes, a...
ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
Specify the column types or set `show_col_types = FALSE` to quiet this message.
• `` -&gt; `...1`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="co"># Look at the first few rows</span></span>
<span id="cb7-2"><a href="#cb7-2"></a><span class="fu">head</span>(imdb_messy, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 29
   ...1 color director_name  num_critic_for_reviews duration
  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;                           &lt;dbl&gt;    &lt;dbl&gt;
1     1 Color James Cameron                     723      178
2     2 Color Gore Verbinski                    302      169
3     3 Color Sam Mendes                        602      148
# ℹ 24 more variables: director_facebook_likes &lt;dbl&gt;,
#   actor_3_facebook_likes &lt;dbl&gt;, actor_2_name &lt;chr&gt;,
#   actor_1_facebook_likes &lt;dbl&gt;, gross &lt;dbl&gt;, genres &lt;chr&gt;,
#   actor_1_name &lt;chr&gt;, movie_title &lt;chr&gt;, num_voted_users &lt;dbl&gt;,
#   cast_total_facebook_likes &lt;dbl&gt;, actor_3_name &lt;chr&gt;,
#   facenumber_in_poster &lt;dbl&gt;, plot_keywords &lt;chr&gt;, movie_imdb_link &lt;chr&gt;,
#   num_user_for_reviews &lt;dbl&gt;, language &lt;chr&gt;, country &lt;chr&gt;, …</code></pre>
</div>
</div>
</section><section id="part-b-1" class="level4" data-number="20.5.2.2"><h4 data-number="20.5.2.2" class="anchored" data-anchor-id="part-b-1">
<span class="header-section-number">20.5.2.2</span> Part b</h4>
<p>Absolute file paths can get really long, depending upon our number of sub-folders, and they should not be used when sharing code with other and instead relative file paths should be used. A relative file path describes the location of a file from the current “working directory”, i.e.&nbsp;where RStudio would currently look for on your computer. Check what your working directory is inside this qmd:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co"># This should be the folder where you stored this qmd!</span></span>
<span id="cb9-2"><a href="#cb9-2"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "/Users/moonhalo/Documents/GitHub/portfolio-Zhijun1933/ica"</code></pre>
</div>
</div>
<p>Next, check what the working directory is for the console by typing getwd() in the console. This is probably different, meaning that the relative file paths that will work in your qmd won’t work in the console! You can either exclusively work inside your qmd, or change the working directory in your console, by navigating to the following in the upper toolbar: Session &gt; Set Working Directory &gt; To Source File location.</p>
</section><section id="part-c" class="level4" data-number="20.5.2.3"><h4 data-number="20.5.2.3" class="anchored" data-anchor-id="part-c">
<span class="header-section-number">20.5.2.3</span> Part c</h4>
<p>As a good practice, we created a data folder and saved our data file (imdb_5000_messy.csv) into.</p>
<p>Since our .qmd analysis and .csv data live in the same project, we don’t have to write out absolute file paths that go all the way to the root directory. We can use relative file paths that start from where our code file exists to where the data file exist:</p>
<ul>
<li>On a Mac: ../data/imdb_5000_messy.csv</li>
<li>On Windows: .._5000_messy.csv or ..\data\imdb_5000_messy.csv</li>
</ul>
<p>NOTE: .. means go up one level in the file hierarchy, ie, go to the parent folder/directory.</p>
<p>Putting this together, use read_csv() with the appropriate relative file path to import your data into RStudio. Save this as imdb_temp (temp for “temporary”). Convince yourself that this worked, i.e.&nbsp;you get the same dataset as imdb_messy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="co"># Using a relative path</span></span>
<span id="cb11-2"><a href="#cb11-2"></a><span class="co"># imdb_temp &lt;- read_csv("../data/imdb_5000_messy.csv")</span></span>
<span id="cb11-3"><a href="#cb11-3"></a></span>
<span id="cb11-4"><a href="#cb11-4"></a><span class="co"># For this activity, we'll just reuse the data loaded above</span></span>
<span id="cb11-5"><a href="#cb11-5"></a>imdb_temp <span class="ot">&lt;-</span> imdb_messy</span>
<span id="cb11-6"><a href="#cb11-6"></a></span>
<span id="cb11-7"><a href="#cb11-7"></a><span class="co"># Check they're the same by comparing dimensions</span></span>
<span id="cb11-8"><a href="#cb11-8"></a><span class="fu">dim</span>(imdb_messy) <span class="sc">==</span> <span class="fu">dim</span>(imdb_temp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE TRUE</code></pre>
</div>
</div>
</section><section id="file-paths" class="level4" data-number="20.5.2.4"><h4 data-number="20.5.2.4" class="anchored" data-anchor-id="file-paths">
<span class="header-section-number">20.5.2.4</span> File Paths</h4>
<p>Absolute file paths should be used when referring to files hosed on the web, eg, https://mac-stat.github.io/data/kiva_partners2.csv. In all other instances, relative file paths should be used.</p>
</section><section id="part-d-optional" class="level4" data-number="20.5.2.5"><h4 data-number="20.5.2.5" class="anchored" data-anchor-id="part-d-optional">
<span class="header-section-number">20.5.2.5</span> Part d: OPTIONAL</h4>
<p>Sometimes, we don’t want to import the entire dataset. For example, we might want to… - skips some rows, eg, if they’re just “filler” - only import the first “n” rows, eg, if the dataset is really large - only import a random subset of “n” rows, eg, if the dataset is really large</p>
<p>The “data import cheat sheet” at the top of this qmd, or Google, are handy resources here. As one example…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="co"># Try importing only the first 5 rows</span></span>
<span id="cb13-2"><a href="#cb13-2"></a>sample_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://mac-stat.github.io/data/imdb_5000_messy.csv"</span>, <span class="at">n_max =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
Rows: 5 Columns: 29
── Column specification
──────────────────────────────────────────────────────── Delimiter: "," chr
(12): color, director_name, actor_2_name, genres, actor_1_name, movie_ti... dbl
(17): ...1, num_critic_for_reviews, duration, director_facebook_likes, a...
ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
Specify the column types or set `show_col_types = FALSE` to quiet this message.
• `` -&gt; `...1`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="fu">nrow</span>(sample_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
</section></section><section id="exercise-3-check-data" class="level3" data-number="20.5.3"><h3 data-number="20.5.3" class="anchored" data-anchor-id="exercise-3-check-data">
<span class="header-section-number">20.5.3</span> Exercise 3: Check Data</h3>
<p>After importing new data into RStudio, you MUST do some quick checks of the data. Here are two first steps that are especially useful.</p>
<section id="part-a-2" class="level4" data-number="20.5.3.1"><h4 data-number="20.5.3.1" class="anchored" data-anchor-id="part-a-2">
<span class="header-section-number">20.5.3.1</span> Part a</h4>
<p>Open imdb_messy in the spreadsheet-like viewer by typing View(imdb_messy) in the console. Sort this “spreadsheet” by different variables by clicking on the arrows next to the variable names. Do you notice anything unexpected?</p>
<p><em>When sorting and examining the data in View, I noticed several issues:</em> <em>- The color variable has inconsistent values (B&amp;W, Black and White, color, Color, COLOR)</em> <em>- There are many missing values (NA) across different columns</em> <em>- Some values seem unrealistic or like data entry errors (e.g., extremely high budget numbers)</em></p>
</section><section id="part-b-2" class="level4" data-number="20.5.3.2"><h4 data-number="20.5.3.2" class="anchored" data-anchor-id="part-b-2">
<span class="header-section-number">20.5.3.2</span> Part b</h4>
<p>Do a quick summary() of each variable in the dataset. One way to do this is below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a>imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), as.factor)) <span class="sc">|&gt;</span>  <span class="co"># convert characters to factors in order to summarize</span></span>
<span id="cb17-3"><a href="#cb17-3"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      ...1                  color               director_name 
 Min.   :   1   B&amp;W            :  10   Steven Spielberg:  26  
 1st Qu.:1262   Black and White: 199   Woody Allen     :  22  
 Median :2522   color          :  30   Clint Eastwood  :  20  
 Mean   :2522   Color          :4755   Martin Scorsese :  20  
 3rd Qu.:3782   COLOR          :  30   Ridley Scott    :  17  
 Max.   :5043   NA's           :  19   (Other)         :4834  
                                       NA's            : 104  
 num_critic_for_reviews    duration     director_facebook_likes
 Min.   :  1.0          Min.   :  7.0   Min.   :    0.0        
 1st Qu.: 50.0          1st Qu.: 93.0   1st Qu.:    7.0        
 Median :110.0          Median :103.0   Median :   49.0        
 Mean   :140.2          Mean   :107.2   Mean   :  686.5        
 3rd Qu.:195.0          3rd Qu.:118.0   3rd Qu.:  194.5        
 Max.   :813.0          Max.   :511.0   Max.   :23000.0        
 NA's   :50             NA's   :15      NA's   :104            
 actor_3_facebook_likes          actor_2_name  actor_1_facebook_likes
 Min.   :    0.0        Morgan Freeman :  20   Min.   :     0        
 1st Qu.:  133.0        Charlize Theron:  15   1st Qu.:   614        
 Median :  371.5        Brad Pitt      :  14   Median :   988        
 Mean   :  645.0        James Franco   :  11   Mean   :  6560        
 3rd Qu.:  636.0        Meryl Streep   :  11   3rd Qu.: 11000        
 Max.   :23000.0        (Other)        :4959   Max.   :640000        
 NA's   :23             NA's           :  13   NA's   :7             
     gross                            genres             actor_1_name 
 Min.   :      162   Drama               : 236   Robert De Niro:  49  
 1st Qu.:  5340988   Comedy              : 209   Johnny Depp   :  41  
 Median : 25517500   Comedy|Drama        : 191   Nicolas Cage  :  33  
 Mean   : 48468408   Comedy|Drama|Romance: 187   J.K. Simmons  :  31  
 3rd Qu.: 62309438   Comedy|Romance      : 158   Bruce Willis  :  30  
 Max.   :760505847   Drama|Romance       : 152   (Other)       :4852  
 NA's   :884         (Other)             :3910   NA's          :   7  
                    movie_title   num_voted_users   cast_total_facebook_likes
 Ben-Hur&nbsp;                 :   3   Min.   :      5   Min.   :     0           
 Halloween&nbsp;               :   3   1st Qu.:   8594   1st Qu.:  1411           
 Home&nbsp;                    :   3   Median :  34359   Median :  3090           
 King Kong&nbsp;               :   3   Mean   :  83668   Mean   :  9699           
 Pan&nbsp;                     :   3   3rd Qu.:  96309   3rd Qu.: 13756           
 The Fast and the Furious&nbsp;:   3   Max.   :1689764   Max.   :656730           
 (Other)                  :5025                                              
         actor_3_name  facenumber_in_poster
 Ben Mendelsohn:   8   Min.   : 0.000      
 John Heard    :   8   1st Qu.: 0.000      
 Steve Coogan  :   8   Median : 1.000      
 Anne Hathaway :   7   Mean   : 1.371      
 Jon Gries     :   7   3rd Qu.: 2.000      
 (Other)       :4982   Max.   :43.000      
 NA's          :  23   NA's   :13          
                                                                           plot_keywords 
 based on novel                                                                   :   4  
 1940s|child hero|fantasy world|orphan|reference to peter pan                     :   3  
 alien friendship|alien invasion|australia|flying car|mother daughter relationship:   3  
 animal name in title|ape abducts a woman|gorilla|island|king kong                :   3  
 assistant|experiment|frankenstein|medical student|scientist                      :   3  
 (Other)                                                                          :4874  
 NA's                                                                             : 153  
                                             movie_imdb_link
 http://www.imdb.com/title/tt0077651/?ref_=fn_tt_tt_1:   3  
 http://www.imdb.com/title/tt0232500/?ref_=fn_tt_tt_1:   3  
 http://www.imdb.com/title/tt0360717/?ref_=fn_tt_tt_1:   3  
 http://www.imdb.com/title/tt1976009/?ref_=fn_tt_tt_1:   3  
 http://www.imdb.com/title/tt2224026/?ref_=fn_tt_tt_1:   3  
 http://www.imdb.com/title/tt2638144/?ref_=fn_tt_tt_1:   3  
 (Other)                                             :5025  
 num_user_for_reviews     language       country       content_rating
 Min.   :   1.0       English :4704   USA    :3807   R        :2118  
 1st Qu.:  65.0       French  :  73   UK     : 448   PG-13    :1461  
 Median : 156.0       Spanish :  40   France : 154   PG       : 701  
 Mean   : 272.8       Hindi   :  28   Canada : 126   Not Rated: 116  
 3rd Qu.: 326.0       Mandarin:  26   Germany:  97   G        : 112  
 Max.   :5060.0       (Other) : 160   (Other): 406   (Other)  : 232  
 NA's   :21           NA's    :  12   NA's   :   5   NA's     : 303  
     budget            title_year   actor_2_facebook_likes   imdb_score   
 Min.   :2.180e+02   Min.   :1916   Min.   :     0         Min.   :1.600  
 1st Qu.:6.000e+06   1st Qu.:1999   1st Qu.:   281         1st Qu.:5.800  
 Median :2.000e+07   Median :2005   Median :   595         Median :6.600  
 Mean   :3.975e+07   Mean   :2002   Mean   :  1652         Mean   :6.442  
 3rd Qu.:4.500e+07   3rd Qu.:2011   3rd Qu.:   918         3rd Qu.:7.200  
 Max.   :1.222e+10   Max.   :2016   Max.   :137000         Max.   :9.500  
 NA's   :492         NA's   :108    NA's   :13                            
  aspect_ratio   movie_facebook_likes
 Min.   : 1.18   Min.   :     0      
 1st Qu.: 1.85   1st Qu.:     0      
 Median : 2.35   Median :   166      
 Mean   : 2.22   Mean   :  7526      
 3rd Qu.: 2.35   3rd Qu.:  3000      
 Max.   :16.00   Max.   :349000      
 NA's   :329                         </code></pre>
</div>
</div>
<p>Follow-up: - What type of info is provided on quantitative variables? <em>For quantitative variables, the summary provides the minimum, 1st quartile, median, mean, 3rd quartile, and maximum values, along with the count of NA values.</em></p>
<ul>
<li><p>What type of info is provided on categorical variables? <em>For categorical variables (factors), the summary shows the frequency counts for each category and the number of NA values.</em></p></li>
<li><p>What stands out to you in these summaries? Is there anything you’d need to clean before using this data? <em>Several issues stand out:</em> <em>1. The color variable has inconsistent categories</em> <em>2. There are many NA values in multiple columns (e.g., gross, budget, plot_keywords)</em> <em>3. Some variables have very skewed distributions (e.g., Facebook likes)</em> <em>4. There are some unusual values (like the maximum budget of 1.22e+10)</em></p></li>
</ul></section></section><section id="exercise-4-clean-data-factor-variables-1" class="level3" data-number="20.5.4"><h3 data-number="20.5.4" class="anchored" data-anchor-id="exercise-4-clean-data-factor-variables-1">
<span class="header-section-number">20.5.4</span> Exercise 4: Clean Data: Factor Variables 1</h3>
<p>If you didn’t already in Exercise 3, check out the color variable in the imdb_messy dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="co"># Let's see all the unique values in the color variable</span></span>
<span id="cb19-2"><a href="#cb19-2"></a>imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="#cb19-3"></a>  <span class="fu">count</span>(color)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  color               n
  &lt;chr&gt;           &lt;int&gt;
1 B&amp;W                10
2 Black and White   199
3 COLOR              30
4 Color            4755
5 color              30
6 &lt;NA&gt;               19</code></pre>
</div>
</div>
<p>What’s goofy about this / what do we need to fix? <em>The color variable has inconsistent values that essentially represent the same categories:</em> <em>- “B&amp;W” and “Black and White” both represent black and white films</em> <em>- “COLOR”, “Color”, and “color” all represent color films</em> <em>- There are also 19 NA values</em></p>
<p>More specifically, what different categories does the color variable take, and how many movies fall into each of these categories? <em>As shown in the count above:</em> <em>- B&amp;W: 10 movies</em> <em>- Black and White: 199 movies</em> <em>- COLOR: 30 movies</em> <em>- Color: 4755 movies</em> <em>- color: 30 movies</em> <em>- NA: 19 movies</em></p>
</section><section id="exercise-5-clean-data-factor-variables-2" class="level3" data-number="20.5.5"><h3 data-number="20.5.5" class="anchored" data-anchor-id="exercise-5-clean-data-factor-variables-2">
<span class="header-section-number">20.5.5</span> Exercise 5: Clean Data: Factor Variables 2</h3>
<p>When working with categorical variables like color, the categories must be “clean”, i.e.&nbsp;consistent and in the correct format. Let’s make that happen.</p>
<section id="part-a-3" class="level4" data-number="20.5.5.1"><h4 data-number="20.5.5.1" class="anchored" data-anchor-id="part-a-3">
<span class="header-section-number">20.5.5.1</span> Part a</h4>
<p>We could open the .csv file in, say, Excel or Google sheets, clean up the color variable, save a clean copy, and then reimport that into RStudio. BUT that would be the wrong thing to do. Why is it important to use R code, which we then save inside this qmd, to clean our data?</p>
<p><em>It’s important to use R code to clean data for several reasons:</em> <em>1. Reproducibility - The entire data cleaning process is documented and can be rerun</em> <em>2. Transparency - Others can see exactly what changes were made</em> <em>3. Consistency - The same process will be applied every time</em> <em>4. Efficiency - If the raw data changes, we can easily rerun our cleaning code</em> <em>5. Version control - Changes to our cleaning process can be tracked</em></p>
</section><section id="part-b-3" class="level4" data-number="20.5.5.2"><h4 data-number="20.5.5.2" class="anchored" data-anchor-id="part-b-3">
<span class="header-section-number">20.5.5.2</span> Part b</h4>
<p>Let’s use R code to change the color variable so that it appropriately combines the various categories into only 2: Color and Black_White. We’ve learned a couple sets of string-related tools that could be handy here. First, starting with the imdb_messy data, change the color variable using one of the functions we learned in the Factors lesson.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="co"># Using fct_recode to recode the color variable</span></span>
<span id="cb21-2"><a href="#cb21-2"></a>imdb_temp <span class="ot">&lt;-</span> imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb21-3"><a href="#cb21-3"></a>  <span class="fu">mutate</span>(<span class="at">color =</span> <span class="fu">fct_recode</span>(color,</span>
<span id="cb21-4"><a href="#cb21-4"></a>                          <span class="st">"Color"</span> <span class="ot">=</span> <span class="st">"COLOR"</span>,</span>
<span id="cb21-5"><a href="#cb21-5"></a>                          <span class="st">"Color"</span> <span class="ot">=</span> <span class="st">"color"</span>,</span>
<span id="cb21-6"><a href="#cb21-6"></a>                          <span class="st">"Black_White"</span> <span class="ot">=</span> <span class="st">"B&amp;W"</span>,</span>
<span id="cb21-7"><a href="#cb21-7"></a>                          <span class="st">"Black_White"</span> <span class="ot">=</span> <span class="st">"Black and White"</span>))</span>
<span id="cb21-8"><a href="#cb21-8"></a></span>
<span id="cb21-9"><a href="#cb21-9"></a><span class="co"># Check the result</span></span>
<span id="cb21-10"><a href="#cb21-10"></a>imdb_temp <span class="sc">|&gt;</span></span>
<span id="cb21-11"><a href="#cb21-11"></a>  <span class="fu">count</span>(color)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  color           n
  &lt;fct&gt;       &lt;int&gt;
1 Black_White   209
2 Color        4815
3 &lt;NA&gt;           19</code></pre>
</div>
</div>
</section><section id="part-c-1" class="level4" data-number="20.5.5.3"><h4 data-number="20.5.5.3" class="anchored" data-anchor-id="part-c-1">
<span class="header-section-number">20.5.5.3</span> Part c</h4>
<p>Repeat Part b using one of our string functions from the String lesson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="co"># Using str_replace to clean the color variable</span></span>
<span id="cb23-2"><a href="#cb23-2"></a>imdb_temp2 <span class="ot">&lt;-</span> imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3"></a>  <span class="fu">mutate</span>(<span class="at">color =</span> <span class="fu">str_replace</span>(color, <span class="st">"COLOR"</span>, <span class="st">"Color"</span>),</span>
<span id="cb23-4"><a href="#cb23-4"></a>         <span class="at">color =</span> <span class="fu">str_replace</span>(color, <span class="st">"color"</span>, <span class="st">"Color"</span>),</span>
<span id="cb23-5"><a href="#cb23-5"></a>         <span class="at">color =</span> <span class="fu">str_replace</span>(color, <span class="st">"B&amp;W"</span>, <span class="st">"Black_White"</span>),</span>
<span id="cb23-6"><a href="#cb23-6"></a>         <span class="at">color =</span> <span class="fu">str_replace</span>(color, <span class="st">"Black and White"</span>, <span class="st">"Black_White"</span>))</span>
<span id="cb23-7"><a href="#cb23-7"></a></span>
<span id="cb23-8"><a href="#cb23-8"></a><span class="co"># Check the result</span></span>
<span id="cb23-9"><a href="#cb23-9"></a>imdb_temp2 <span class="sc">|&gt;</span></span>
<span id="cb23-10"><a href="#cb23-10"></a>  <span class="fu">count</span>(color)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  color           n
  &lt;chr&gt;       &lt;int&gt;
1 Black_White   209
2 Color        4815
3 &lt;NA&gt;           19</code></pre>
</div>
</div>
</section></section><section id="exercise-6-clean-data-missing-data-1" class="level3" data-number="20.5.6"><h3 data-number="20.5.6" class="anchored" data-anchor-id="exercise-6-clean-data-missing-data-1">
<span class="header-section-number">20.5.6</span> Exercise 6: Clean Data: Missing Data 1</h3>
<p>Throughout these exercises, you’ve probably noticed that there’s a bunch of missing data. This is encoded as NA (not available) in R. There are a few questions to address about missing data:</p>
<ol type="1">
<li>How many values are missing data? What’s the volume of the missingness?</li>
<li>Why are some values missing?</li>
<li>What should we do about the missing values?</li>
</ol>
<p>Let’s consider the first 2 questions in this exercise.</p>
<section id="part-a-4" class="level4" data-number="20.5.6.1"><h4 data-number="20.5.6.1" class="anchored" data-anchor-id="part-a-4">
<span class="header-section-number">20.5.6.1</span> Part a</h4>
<p>As a first step, let’s simply understand the volume of NAs. Specifically:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="co"># Count the total number of rows in imdb_messy</span></span>
<span id="cb25-2"><a href="#cb25-2"></a><span class="fu">nrow</span>(imdb_messy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5043</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="co"># Then count the number of NAs in each column</span></span>
<span id="cb27-2"><a href="#cb27-2"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(imdb_messy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     ...1                     color             director_name 
                        0                        19                       104 
   num_critic_for_reviews                  duration   director_facebook_likes 
                       50                        15                       104 
   actor_3_facebook_likes              actor_2_name    actor_1_facebook_likes 
                       23                        13                         7 
                    gross                    genres              actor_1_name 
                      884                         0                         7 
              movie_title           num_voted_users cast_total_facebook_likes 
                        0                         0                         0 
             actor_3_name      facenumber_in_poster             plot_keywords 
                       23                        13                       153 
          movie_imdb_link      num_user_for_reviews                  language 
                        0                        21                        12 
                  country            content_rating                    budget 
                        5                       303                       492 
               title_year    actor_2_facebook_likes                imdb_score 
                      108                        13                         0 
             aspect_ratio      movie_facebook_likes 
                      329                         0 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="co"># Then count the number of NAs in a specific column</span></span>
<span id="cb29-2"><a href="#cb29-2"></a>imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3"></a>  <span class="fu">summarize</span>(<span class="at">na_count =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(actor_1_facebook_likes)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  na_count
     &lt;int&gt;
1        7</code></pre>
</div>
</div>
</section><section id="part-b-4" class="level4" data-number="20.5.6.2"><h4 data-number="20.5.6.2" class="anchored" data-anchor-id="part-b-4">
<span class="header-section-number">20.5.6.2</span> Part b</h4>
<p>As a second step, let’s think about why some values are missing. Study the individual observations with NAs carefully. Why do you think they are missing? Are certain films more likely to have more NAs than others?</p>
<p><em>After examining the data, it appears that:</em> <em>1. Older films tend to have more missing values, especially for Facebook-related data</em> <em>2. Some films may be missing budget or gross data because this information wasn’t publicly available</em> <em>3. Some missing values (like in the actor columns) might be from documentaries or films without traditional actors</em> <em>4. Some films might be missing content ratings if they weren’t officially rated</em></p>
</section><section id="part-c-2" class="level4" data-number="20.5.6.3"><h4 data-number="20.5.6.3" class="anchored" data-anchor-id="part-c-2">
<span class="header-section-number">20.5.6.3</span> Part c</h4>
<p>Consider a more specific example. Obtain a dataset of movies that are missing data on actor_1_facebook_likes. Then explain why you think there are NAs.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="co"># Get films with missing actor_1_facebook_likes</span></span>
<span id="cb31-2"><a href="#cb31-2"></a>films_missing_actor_likes <span class="ot">&lt;-</span> imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(actor_1_facebook_likes))</span>
<span id="cb31-4"><a href="#cb31-4"></a></span>
<span id="cb31-5"><a href="#cb31-5"></a><span class="co"># Examine these films</span></span>
<span id="cb31-6"><a href="#cb31-6"></a>films_missing_actor_likes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 29
   ...1 color director_name     num_critic_for_reviews duration
  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;                              &lt;dbl&gt;    &lt;dbl&gt;
1  4503 Color Léa Pool                              23       97
2  4520 Color Harry Gantz                           12      105
3  4721 Color U. Roberto Romano                      3       80
4  4838 Color Pan Nalin                             15      102
5  4946 Color Amal Al-Agroobi                       NA       62
6  4947 Color Andrew Berends                        12       90
7  4991 Color Jem Cohen                             12      111
# ℹ 24 more variables: director_facebook_likes &lt;dbl&gt;,
#   actor_3_facebook_likes &lt;dbl&gt;, actor_2_name &lt;chr&gt;,
#   actor_1_facebook_likes &lt;dbl&gt;, gross &lt;dbl&gt;, genres &lt;chr&gt;,
#   actor_1_name &lt;chr&gt;, movie_title &lt;chr&gt;, num_voted_users &lt;dbl&gt;,
#   cast_total_facebook_likes &lt;dbl&gt;, actor_3_name &lt;chr&gt;,
#   facenumber_in_poster &lt;dbl&gt;, plot_keywords &lt;chr&gt;, movie_imdb_link &lt;chr&gt;,
#   num_user_for_reviews &lt;dbl&gt;, language &lt;chr&gt;, country &lt;chr&gt;, …</code></pre>
</div>
</div>
<p><em>Looking at these films, it appears they are documentaries or similar non-fiction films that don’t have traditional actors. Since there are no lead actors, there wouldn’t be Facebook likes data for “actor_1”. In these cases, NA makes sense because the field simply doesn’t apply to these films rather than indicating missing information about an actor.</em></p>
</section></section><section id="exercise-7-clean-data-missing-data-2" class="level3" data-number="20.5.7"><h3 data-number="20.5.7" class="anchored" data-anchor-id="exercise-7-clean-data-missing-data-2">
<span class="header-section-number">20.5.7</span> Exercise 7: Clean Data: Missing Data 2</h3>
<p>Next, let’s think about what to do about the missing values. There is no perfect or universal approach here. Rather, we must think carefully about…</p>
<ol type="1">
<li>Why the values are missing?</li>
<li>What we want to do with our data?</li>
<li>What is the impact of removing or replacing missing data on our work / conclusions?</li>
</ol>
<section id="part-a-5" class="level4" data-number="20.5.7.1"><h4 data-number="20.5.7.1" class="anchored" data-anchor-id="part-a-5">
<span class="header-section-number">20.5.7.1</span> Part a</h4>
<p>Calculate the average duration of a film. THINK: How can we deal with the NA’s?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="co"># Calculate average duration, ignoring NA values</span></span>
<span id="cb33-2"><a href="#cb33-2"></a>imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="#cb33-3"></a>  <span class="fu">summarize</span>(<span class="at">avg_duration =</span> <span class="fu">mean</span>(duration, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  avg_duration
         &lt;dbl&gt;
1         107.</code></pre>
</div>
</div>
<p>Follow-up: - How are the NAs dealt with here? Did we have to create and save a new dataset in order to do this analysis?</p>
<p><em>The NAs are handled using the na.rm = TRUE parameter in the mean() function, which tells R to ignore NA values when calculating the mean. We did not need to create a new dataset for this analysis - we simply addressed the NAs within the calculation itself. This approach is convenient for one-off calculations but doesn’t permanently affect the dataset.</em></p>
</section><section id="part-b-5" class="level4" data-number="20.5.7.2"><h4 data-number="20.5.7.2" class="anchored" data-anchor-id="part-b-5">
<span class="header-section-number">20.5.7.2</span> Part b</h4>
<p>Try out the drop_na() function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="co"># Remove all rows with any NA values</span></span>
<span id="cb35-2"><a href="#cb35-2"></a>imdb_complete <span class="ot">&lt;-</span> <span class="fu">drop_na</span>(imdb_messy)</span>
<span id="cb35-3"><a href="#cb35-3"></a></span>
<span id="cb35-4"><a href="#cb35-4"></a><span class="co"># Check how many rows remain</span></span>
<span id="cb35-5"><a href="#cb35-5"></a><span class="fu">nrow</span>(imdb_complete)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3756</code></pre>
</div>
</div>
<p>Follow-up questions: - What did drop_na() do? How many data points are left? <em>The drop_na() function removed all rows that contained at least one NA value in any column. We started with 5,043 rows and ended with only 3,756 rows - meaning we lost 1,287 rows (about 25.5% of our data).</em></p>
<ul>
<li><p>In what situations might this function be a good idea? <em>This function might be a good idea when:</em> <em>- You need complete cases for certain statistical methods that can’t handle NAs</em> <em>- The amount of missing data is small, so you don’t lose much information</em> <em>- The missing data is missing completely at random (MCAR) so removing rows won’t introduce bias</em> <em>- You need a quick, clean dataset for a simple analysis or visualization</em></p></li>
<li><p>In what situations might this function be a bad idea? <em>This function might be a bad idea when:</em> <em>- You lose too much data (as in this case - losing 25% is substantial)</em> <em>- The missing data follows a pattern, so removing rows could introduce bias</em> <em>- The NAs actually represent meaningful information (like in our actor_1_facebook_likes example)</em> <em>- You only need a few variables for your analysis, but you’re removing rows based on NAs in variables you don’t need</em></p></li>
</ul></section><section id="part-c-3" class="level4" data-number="20.5.7.3"><h4 data-number="20.5.7.3" class="anchored" data-anchor-id="part-c-3">
<span class="header-section-number">20.5.7.3</span> Part c</h4>
<p>drop_na() removes data points that have any NA values, even if we don’t care about the variable(s) for which data is missing. This can result in losing a lot of data points that do have data on the variables we actually care about! For example, suppose we only want to explore the relationship between film duration and whether it’s in color. Check out a plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="co"># Try to plot with the full dataset</span></span>
<span id="cb37-2"><a href="#cb37-2"></a><span class="fu">ggplot</span>(imdb_messy, <span class="fu">aes</span>(<span class="at">x =</span> duration, <span class="at">fill =</span> color)) <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 15 rows containing non-finite outside the scale range
(`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="ica-working-with-data-import_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Follow-up: - Create a new dataset with only and all movies that have complete info on duration and color. HINT: You could use !i s.na(___) or drop_na() (differently than above)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="co"># Create dataset with only movies that have complete info on duration and color</span></span>
<span id="cb39-2"><a href="#cb39-2"></a>imdb_duration_color <span class="ot">&lt;-</span> imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb39-3"><a href="#cb39-3"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(duration), <span class="sc">!</span><span class="fu">is.na</span>(color))</span>
<span id="cb39-4"><a href="#cb39-4"></a></span>
<span id="cb39-5"><a href="#cb39-5"></a><span class="co"># Check how many rows remain</span></span>
<span id="cb39-6"><a href="#cb39-6"></a><span class="fu">nrow</span>(imdb_duration_color)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5010</code></pre>
</div>
</div>
<ul>
<li>Use this new dataset to create a new and improved plot.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a><span class="co"># Create improved plot</span></span>
<span id="cb41-2"><a href="#cb41-2"></a><span class="fu">ggplot</span>(imdb_duration_color, <span class="fu">aes</span>(<span class="at">x =</span> duration, <span class="at">fill =</span> color)) <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb41-4"><a href="#cb41-4"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Movie Duration by Color Type"</span>,</span>
<span id="cb41-5"><a href="#cb41-5"></a>       <span class="at">x =</span> <span class="st">"Duration (minutes)"</span>,</span>
<span id="cb41-6"><a href="#cb41-6"></a>       <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb41-7"><a href="#cb41-7"></a>       <span class="at">fill =</span> <span class="st">"Film Type"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="ica-working-with-data-import_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>How many movies remain in your new dataset? Hence why this is better than using the dataset from part b?</li>
</ul>
<p><em>We have 5,010 movies in our new dataset, compared to just 3,756 in the completely clean dataset. This is much better because we’re only removing movies that are missing the specific variables we need for our analysis (duration and color). We’ve kept 1,254 more movies that would have been unnecessarily removed if we had used drop_na() on the entire dataset.</em></p>
</section><section id="part-d" class="level4" data-number="20.5.7.4"><h4 data-number="20.5.7.4" class="anchored" data-anchor-id="part-d">
<span class="header-section-number">20.5.7.4</span> Part d</h4>
<p>In some cases, missing data is more non-data than unknown data. For example, the films with NAs for actor_1_facebook_likes actually have 0 Facebook likes–they don’t even have actors! In these cases, we can replace the NAs with a 0. Use the replace_na() function to create a new dataset (imdb_temp) that replaces the NAs in actor_1_facebook_likes with 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a><span class="co"># Replace NAs in actor_1_facebook_likes with 0</span></span>
<span id="cb42-2"><a href="#cb42-2"></a>imdb_temp <span class="ot">&lt;-</span> imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb42-3"><a href="#cb42-3"></a>  <span class="fu">mutate</span>(<span class="at">actor_1_facebook_likes =</span> <span class="fu">replace_na</span>(actor_1_facebook_likes, <span class="dv">0</span>))</span>
<span id="cb42-4"><a href="#cb42-4"></a></span>
<span id="cb42-5"><a href="#cb42-5"></a><span class="co"># Check if there are any NAs left in that column</span></span>
<span id="cb42-6"><a href="#cb42-6"></a>imdb_temp <span class="sc">|&gt;</span></span>
<span id="cb42-7"><a href="#cb42-7"></a>  <span class="fu">summarize</span>(<span class="at">na_count =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(actor_1_facebook_likes)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  na_count
     &lt;int&gt;
1        0</code></pre>
</div>
</div>
</section></section><section id="exercise-8-new-data-projects" class="level3" data-number="20.5.8"><h3 data-number="20.5.8" class="anchored" data-anchor-id="exercise-8-new-data-projects">
<span class="header-section-number">20.5.8</span> Exercise 8: New Data + Projects</h3>
<p>Let’s practice the above ideas while also planting some seeds for the course project. Each group will pick and analyze their own dataset. The people you’re sitting with today aren’t necessarily your project groups! BUT do some brainstorming together:</p>
<ol type="1">
<li><p>Share with each other: What are some personal hobbies or passions or things you’ve been thinking about or things you’d like to learn more about? Don’t think too hard about this! Just share what’s at the top of mind today.</p></li>
<li><p>Each individual: Find a dataset online that’s related to one of the topics you shared in the above prompt.</p></li>
<li><p>Discuss what data you found with your group!</p></li>
<li><p>Load the data into RStudio, perform some basic checks, and perform some preliminary cleaning, as necessary.</p></li>
</ol>
<p><em>For this exercise, I found a dataset about global coffee production. Let me demonstrate how I would approach exploring this dataset:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a><span class="co"># Load a sample dataset - using mtcars which is built into R</span></span>
<span id="cb44-2"><a href="#cb44-2"></a><span class="co"># In a real scenario, you would load your own dataset</span></span>
<span id="cb44-3"><a href="#cb44-3"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb44-4"><a href="#cb44-4"></a></span>
<span id="cb44-5"><a href="#cb44-5"></a><span class="co"># Basic checks</span></span>
<span id="cb44-6"><a href="#cb44-6"></a><span class="fu">head</span>(mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="co"># Check structure</span></span>
<span id="cb46-2"><a href="#cb46-2"></a><span class="fu">str</span>(mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a><span class="co"># Check for missing values - mtcars doesn't have NAs, but this is how you'd check</span></span>
<span id="cb48-2"><a href="#cb48-2"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(mtcars))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> mpg  cyl disp   hp drat   wt qsec   vs   am gear carb 
   0    0    0    0    0    0    0    0    0    0    0 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a><span class="co"># Basic cleaning demonstration - convert categorical variables to factors</span></span>
<span id="cb50-2"><a href="#cb50-2"></a>mtcars_clean <span class="ot">&lt;-</span> mtcars <span class="sc">|&gt;</span></span>
<span id="cb50-3"><a href="#cb50-3"></a>  <span class="fu">mutate</span>(</span>
<span id="cb50-4"><a href="#cb50-4"></a>    <span class="at">cyl =</span> <span class="fu">as.factor</span>(cyl),</span>
<span id="cb50-5"><a href="#cb50-5"></a>    <span class="at">vs =</span> <span class="fu">as.factor</span>(vs),</span>
<span id="cb50-6"><a href="#cb50-6"></a>    <span class="at">am =</span> <span class="fu">as.factor</span>(am),</span>
<span id="cb50-7"><a href="#cb50-7"></a>    <span class="at">gear =</span> <span class="fu">as.factor</span>(gear),</span>
<span id="cb50-8"><a href="#cb50-8"></a>    <span class="at">carb =</span> <span class="fu">as.factor</span>(carb)</span>
<span id="cb50-9"><a href="#cb50-9"></a>  )</span>
<span id="cb50-10"><a href="#cb50-10"></a></span>
<span id="cb50-11"><a href="#cb50-11"></a><span class="co"># Create quick visualization to explore the data</span></span>
<span id="cb50-12"><a href="#cb50-12"></a><span class="fu">ggplot</span>(mtcars_clean, <span class="fu">aes</span>(<span class="at">x =</span> wt, <span class="at">y =</span> mpg, <span class="at">color =</span> cyl)) <span class="sc">+</span></span>
<span id="cb50-13"><a href="#cb50-13"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb50-14"><a href="#cb50-14"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Car Weight vs. Fuel Efficiency by Cylinder Count"</span>,</span>
<span id="cb50-15"><a href="#cb50-15"></a>       <span class="at">x =</span> <span class="st">"Weight (1000 lbs)"</span>,</span>
<span id="cb50-16"><a href="#cb50-16"></a>       <span class="at">y =</span> <span class="st">"Miles Per Gallon"</span>,</span>
<span id="cb50-17"><a href="#cb50-17"></a>       <span class="at">color =</span> <span class="st">"Cylinders"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="ica-working-with-data-import_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>This example shows the basic workflow: loading data, checking its structure, identifying missing values, cleaning as needed, and creating exploratory visualizations.</em></p>


<!-- -->

</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../ica/ica-working with strings.html" class="pagination-link" aria-label="Working with Strings">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Working with Strings</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../ica/ica-EDA.html" class="pagination-link" aria-label="Exploratory Data Analysis">
        <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb51" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb51-1"><a href="#cb51-1"></a><span class="co">---</span></span>
<span id="cb51-2"><a href="#cb51-2"></a><span class="an">title:</span><span class="co"> "Data Import"</span></span>
<span id="cb51-3"><a href="#cb51-3"></a><span class="an">format:</span><span class="co"> html</span></span>
<span id="cb51-4"><a href="#cb51-4"></a><span class="co">---</span></span>
<span id="cb51-5"><a href="#cb51-5"></a></span>
<span id="cb51-6"><a href="#cb51-6"></a><span class="fu">## Learning Goals</span></span>
<span id="cb51-7"><a href="#cb51-7"></a></span>
<span id="cb51-8"><a href="#cb51-8"></a>Get a glimpse into how to...</span>
<span id="cb51-9"><a href="#cb51-9"></a></span>
<span id="cb51-10"><a href="#cb51-10"></a><span class="ss">-   </span>find existing data sets</span>
<span id="cb51-11"><a href="#cb51-11"></a><span class="ss">-   </span>save data sets locally</span>
<span id="cb51-12"><a href="#cb51-12"></a><span class="ss">-   </span>load data into RStudio</span>
<span id="cb51-13"><a href="#cb51-13"></a><span class="ss">-   </span>do some preliminary data checking and cleaning steps before further wrangling / visualization:</span>
<span id="cb51-14"><a href="#cb51-14"></a><span class="ss">    -   </span>make sure variables are properly formatted</span>
<span id="cb51-15"><a href="#cb51-15"></a><span class="ss">    -   </span>deal with missing values</span>
<span id="cb51-16"><a href="#cb51-16"></a></span>
<span id="cb51-17"><a href="#cb51-17"></a>NOTE: These skills are best learned through practice.</span>
<span id="cb51-18"><a href="#cb51-18"></a>We'll just scratch the surface here.</span>
<span id="cb51-19"><a href="#cb51-19"></a></span>
<span id="cb51-20"><a href="#cb51-20"></a><span class="fu">## Additional Resources</span></span>
<span id="cb51-21"><a href="#cb51-21"></a></span>
<span id="cb51-22"><a href="#cb51-22"></a>For more information about the topics covered in this chapter, refer to the resources below:</span>
<span id="cb51-23"><a href="#cb51-23"></a></span>
<span id="cb51-24"><a href="#cb51-24"></a><span class="ss">-   </span><span class="co">[</span><span class="ot">Using the import wizard (YouTube)</span><span class="co">](https://www.youtube.com/watch?v=EWz9siRXLdM)</span> by Lisa Lendway</span>
<span id="cb51-25"><a href="#cb51-25"></a><span class="ss">-   </span><span class="co">[</span><span class="ot">data import cheat sheet (pdf)</span><span class="co">](https://posit.co/wp-content/uploads/2022/10/data-import-cheatsheet.pdf)</span></span>
<span id="cb51-26"><a href="#cb51-26"></a><span class="ss">-   </span><span class="co">[</span><span class="ot">readr documentation (html)</span><span class="co">](https://readr.tidyverse.org/)</span></span>
<span id="cb51-27"><a href="#cb51-27"></a><span class="ss">-   </span><span class="co">[</span><span class="ot">Data import (html)</span><span class="co">](https://r4ds.had.co.nz/data-import.html)</span> by Wickham and Grolemund</span>
<span id="cb51-28"><a href="#cb51-28"></a><span class="ss">-   </span><span class="co">[</span><span class="ot">Missing data (html)</span><span class="co">](https://r4ds.had.co.nz/tidy-data.html#missing-values-3)</span> by Wickham and Grolemund</span>
<span id="cb51-29"><a href="#cb51-29"></a><span class="ss">-   </span><span class="co">[</span><span class="ot">Data intake (html)</span><span class="co">](https://mdsr-book.github.io/mdsr2e/ch-dataI.html)</span> by Baumer, Kaplan, and Horton</span>
<span id="cb51-30"><a href="#cb51-30"></a></span>
<span id="cb51-31"><a href="#cb51-31"></a><span class="fu">## 14.1 Review</span></span>
<span id="cb51-32"><a href="#cb51-32"></a></span>
<span id="cb51-33"><a href="#cb51-33"></a>WHERE ARE WE?</span>
<span id="cb51-34"><a href="#cb51-34"></a></span>
<span id="cb51-35"><a href="#cb51-35"></a>We've thus far focused on data preparation and visualization:</span>
<span id="cb51-36"><a href="#cb51-36"></a></span>
<span id="cb51-37"><a href="#cb51-37"></a>What's coming up?</span>
<span id="cb51-38"><a href="#cb51-38"></a></span>
<span id="cb51-39"><a href="#cb51-39"></a>In the last few weeks we'll focus on data storytelling through the completion of a course project.</span>
<span id="cb51-40"><a href="#cb51-40"></a></span>
<span id="cb51-41"><a href="#cb51-41"></a>This week we'll address the other gaps in the workflow: data collection and analysis.</span>
<span id="cb51-42"><a href="#cb51-42"></a>We'll do so in the context of starting a data project...</span>
<span id="cb51-43"><a href="#cb51-43"></a></span>
<span id="cb51-44"><a href="#cb51-44"></a><span class="fu">## 14.2 Data Import</span></span>
<span id="cb51-45"><a href="#cb51-45"></a></span>
<span id="cb51-46"><a href="#cb51-46"></a><span class="fu">### Starting Data Project</span></span>
<span id="cb51-47"><a href="#cb51-47"></a></span>
<span id="cb51-48"><a href="#cb51-48"></a>Any data science project consists of two phases:</span>
<span id="cb51-49"><a href="#cb51-49"></a></span>
<span id="cb51-50"><a href="#cb51-50"></a><span class="ss">1.  </span>**Data Collection** A data project starts with data! Thus far, you've either been given data, or used TidyTuesday data. In this unit:</span>
<span id="cb51-51"><a href="#cb51-51"></a><span class="ss">    -   </span>We WILL explore how to find data, save data, import this data into RStudio, and do some preliminary data cleaning.</span>
<span id="cb51-52"><a href="#cb51-52"></a><span class="ss">    -   </span>We will NOT discuss how to collect data from scratch (e.g. via experiment, observational study, or survey).</span>
<span id="cb51-53"><a href="#cb51-53"></a><span class="ss">2.  </span>**Data Analysis** Once we have data, we need to do some analysis. In this unit...</span>
<span id="cb51-54"><a href="#cb51-54"></a><span class="ss">    -   </span>We WILL bring together our wrangling &amp; visualization tools to discuss exploratory data analysis (EDA). EDA is the process of getting to know our data, obtaining insights from data, and using these insights to formulate, refine, and explore research questions.</span>
<span id="cb51-55"><a href="#cb51-55"></a><span class="ss">    -   </span>We will NOT explore other types of analysis, such as modeling &amp; prediction–if interested, take STAT 155 and 253 to learn more about these topics.</span>
<span id="cb51-56"><a href="#cb51-56"></a></span>
<span id="cb51-57"><a href="#cb51-57"></a>NOTE: These skills are best learned through practice.</span>
<span id="cb51-58"><a href="#cb51-58"></a>We'll just scratch the surface here.</span>
<span id="cb51-59"><a href="#cb51-59"></a></span>
<span id="cb51-60"><a href="#cb51-60"></a><span class="fu">### File Formats</span></span>
<span id="cb51-61"><a href="#cb51-61"></a></span>
<span id="cb51-62"><a href="#cb51-62"></a>Before exploring how to find, store, import, check, and clean data, it's important to recognize that data can be stored in various formats.</span>
<span id="cb51-63"><a href="#cb51-63"></a>We've been working with .csv files.</span>
<span id="cb51-64"><a href="#cb51-64"></a>In the background, these have "comma-separated values" (csv):</span>
<span id="cb51-65"><a href="#cb51-65"></a></span>
<span id="cb51-66"><a href="#cb51-66"></a>But there are many other common file types.</span>
<span id="cb51-67"><a href="#cb51-67"></a>For example, the following are compatible with R:</span>
<span id="cb51-68"><a href="#cb51-68"></a></span>
<span id="cb51-69"><a href="#cb51-69"></a><span class="ss">-   </span>Excel files: .xls, .xlsx</span>
<span id="cb51-70"><a href="#cb51-70"></a><span class="ss">-   </span>R "data serialization" files: .rds</span>
<span id="cb51-71"><a href="#cb51-71"></a><span class="ss">-   </span>files with tab-separated values: .tsv</span>
<span id="cb51-72"><a href="#cb51-72"></a></span>
<span id="cb51-73"><a href="#cb51-73"></a><span class="fu">### STEP 1: Find Data</span></span>
<span id="cb51-74"><a href="#cb51-74"></a></span>
<span id="cb51-75"><a href="#cb51-75"></a>Check the Datasets page for information about how to find a dataset that fits your needs.</span>
<span id="cb51-76"><a href="#cb51-76"></a></span>
<span id="cb51-77"><a href="#cb51-77"></a><span class="fu">### STEP 2: Save Data Locally</span></span>
<span id="cb51-78"><a href="#cb51-78"></a></span>
<span id="cb51-79"><a href="#cb51-79"></a>Unless we're just doing a quick, one-off data analysis, it's important to store a local copy of a data file, i.e. save the data file to our own machine.</span>
<span id="cb51-80"><a href="#cb51-80"></a></span>
<span id="cb51-81"><a href="#cb51-81"></a>Mainly, we shouldn't rely on another person / institution to store a data file online, in the same place, forever!</span>
<span id="cb51-82"><a href="#cb51-82"></a></span>
<span id="cb51-83"><a href="#cb51-83"></a><span class="fu">#### Recommendations when Saving Data</span></span>
<span id="cb51-84"><a href="#cb51-84"></a></span>
<span id="cb51-85"><a href="#cb51-85"></a>When saving your data, make sure they are: - in a nice format, eg, a csv file format - where you'll be able to find it again - ideally, within a folder that's dedicated to the related project / assignment - alongside the qmd file(s) where you'll record your analysis of the data</span>
<span id="cb51-86"><a href="#cb51-86"></a></span>
<span id="cb51-87"><a href="#cb51-87"></a><span class="fu">### STEP 3: Import Data to RStudio</span></span>
<span id="cb51-88"><a href="#cb51-88"></a></span>
<span id="cb51-89"><a href="#cb51-89"></a>Once we have a local copy of our data file, we need to get it into RStudio!</span>
<span id="cb51-90"><a href="#cb51-90"></a>This process depends on 2 things: (1) the file type (e.g. .csv); and (2) the file location, i.e. where it's stored on your computer.</span>
<span id="cb51-91"><a href="#cb51-91"></a></span>
<span id="cb51-92"><a href="#cb51-92"></a><span class="fu">#### 1. FILE TYPE</span></span>
<span id="cb51-93"><a href="#cb51-93"></a></span>
<span id="cb51-94"><a href="#cb51-94"></a>The file type indicates which function we'll need to import it.</span>
<span id="cb51-95"><a href="#cb51-95"></a>The table below lists some common import functions and when to use them.</span>
<span id="cb51-96"><a href="#cb51-96"></a></span>
<span id="cb51-97"><a href="#cb51-97"></a>| Function     | Data file type                                            |</span>
<span id="cb51-98"><a href="#cb51-98"></a>|--------------|-----------------------------------------------------------|</span>
<span id="cb51-99"><a href="#cb51-99"></a>| read_csv()   | .csv - you can save Excel files and Google Sheets as .csv |</span>
<span id="cb51-100"><a href="#cb51-100"></a>| read_delim() | other delimited formats (tab, space, etc.)                |</span>
<span id="cb51-101"><a href="#cb51-101"></a>| read_sheet() | Google Sheet                                              |</span>
<span id="cb51-102"><a href="#cb51-102"></a>| st_read()    | spatial data shapefile                                    |</span>
<span id="cb51-103"><a href="#cb51-103"></a></span>
<span id="cb51-104"><a href="#cb51-104"></a>NOTE: In comparison to read.csv, read_csv is faster when importing large data files and can more easily parse complicated datasets, eg, with dates, times, percentages.</span>
<span id="cb51-105"><a href="#cb51-105"></a></span>
<span id="cb51-106"><a href="#cb51-106"></a><span class="fu">#### 2. FILE LOCATION</span></span>
<span id="cb51-107"><a href="#cb51-107"></a></span>
<span id="cb51-108"><a href="#cb51-108"></a>To import the data, we apply the appropriate function from above to the file path.</span>
<span id="cb51-109"><a href="#cb51-109"></a></span>
<span id="cb51-110"><a href="#cb51-110"></a>A file path is an address to where the file is stored on our computer or the web.</span>
<span id="cb51-111"><a href="#cb51-111"></a></span>
<span id="cb51-112"><a href="#cb51-112"></a>Consider "1600 Grand Ave, St. Paul, MN 55105".</span>
<span id="cb51-113"><a href="#cb51-113"></a>Think about how different parts of the address give increasingly more specific information about the location.</span>
<span id="cb51-114"><a href="#cb51-114"></a>"St. Paul, MN 55105" tells us the city and smaller region within the city, "Grand Ave" tells us the street, and "1600" tells us the specific location on the street.</span>
<span id="cb51-115"><a href="#cb51-115"></a></span>
<span id="cb51-116"><a href="#cb51-116"></a>In the example below, the file path is absolute where it tells us the location giving more and more specific information as you read it from left to right.</span>
<span id="cb51-117"><a href="#cb51-117"></a></span>
<span id="cb51-118"><a href="#cb51-118"></a><span class="ss">-   </span>"\~", on an Apple computer, tells you that you are looking in the user's home directory.</span>
<span id="cb51-119"><a href="#cb51-119"></a><span class="ss">-   </span>"Desktop" tells you to go to the Desktop within that home directory.</span>
<span id="cb51-120"><a href="#cb51-120"></a><span class="ss">-   </span>"112" tells you that you are looking in the 112 folder on the Desktop.</span>
<span id="cb51-121"><a href="#cb51-121"></a><span class="ss">-   </span>"data" tells you to next go in the data folder in the 112 folder.</span>
<span id="cb51-122"><a href="#cb51-122"></a><span class="ss">-   </span>"my_data.csv" tells you that you are looking for a file called my_data.csv location within the data folder.</span>
<span id="cb51-123"><a href="#cb51-123"></a></span>
<span id="cb51-124"><a href="#cb51-124"></a><span class="in">``` r</span></span>
<span id="cb51-125"><a href="#cb51-125"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb51-126"><a href="#cb51-126"></a>my_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"~/Desktop/112/data/my_data.csv"</span>)</span>
<span id="cb51-127"><a href="#cb51-127"></a><span class="in">```</span></span>
<span id="cb51-128"><a href="#cb51-128"></a></span>
<span id="cb51-129"><a href="#cb51-129"></a>Absolute file paths should only be used when reading files hosted on the web.</span>
<span id="cb51-130"><a href="#cb51-130"></a>Otherwise, relative file paths should be used.</span>
<span id="cb51-131"><a href="#cb51-131"></a>Relative file paths as the name suggest is relative to the file where the data file is read.</span>
<span id="cb51-132"><a href="#cb51-132"></a></span>
<span id="cb51-133"><a href="#cb51-133"></a><span class="in">``` r</span></span>
<span id="cb51-134"><a href="#cb51-134"></a><span class="co"># assume the code containing this script is under a folder called /src which</span></span>
<span id="cb51-135"><a href="#cb51-135"></a><span class="co"># is at the same level of the /data folder</span></span>
<span id="cb51-136"><a href="#cb51-136"></a></span>
<span id="cb51-137"><a href="#cb51-137"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb51-138"><a href="#cb51-138"></a>my_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../data/my_data.csv"</span>)</span>
<span id="cb51-139"><a href="#cb51-139"></a><span class="in">```</span></span>
<span id="cb51-140"><a href="#cb51-140"></a></span>
<span id="cb51-141"><a href="#cb51-141"></a><span class="fu">### STEP 4: Check &amp; Clean Data</span></span>
<span id="cb51-142"><a href="#cb51-142"></a></span>
<span id="cb51-143"><a href="#cb51-143"></a>Once the data is loaded, ask yourself a few questions:</span>
<span id="cb51-144"><a href="#cb51-144"></a></span>
<span id="cb51-145"><a href="#cb51-145"></a><span class="ss">1.  </span>What's the structure of the data?</span>
<span id="cb51-146"><a href="#cb51-146"></a><span class="ss">    -   </span>Use str() to learn about the numbers of variables and observations as well as the classes or types of variables (date, location, string, factor, number, boolean, etc.)</span>
<span id="cb51-147"><a href="#cb51-147"></a><span class="ss">    -   </span>Use head() to view the top of the data table</span>
<span id="cb51-148"><a href="#cb51-148"></a><span class="ss">    -   </span>Use View() to view the data in a spreadsheet-like viewer, use this command in the Console but don't include it in your qmd files since it will prevent your project from rendering.</span>
<span id="cb51-149"><a href="#cb51-149"></a><span class="ss">2.  </span>Is there anything goofy that we need to clean before we can analyze the data?</span>
<span id="cb51-150"><a href="#cb51-150"></a><span class="ss">    -   </span>Is it in a tidy format?</span>
<span id="cb51-151"><a href="#cb51-151"></a><span class="ss">    -   </span>How many rows are there? What does the row mean? What is an observation?</span>
<span id="cb51-152"><a href="#cb51-152"></a><span class="ss">    -   </span>Is there consistent formatting for categorical variables?</span>
<span id="cb51-153"><a href="#cb51-153"></a><span class="ss">    -   </span>Is there missing data that needs to be addressed?</span>
<span id="cb51-154"><a href="#cb51-154"></a></span>
<span id="cb51-155"><a href="#cb51-155"></a><span class="fu">### STEP 5: Understand Data</span></span>
<span id="cb51-156"><a href="#cb51-156"></a></span>
<span id="cb51-157"><a href="#cb51-157"></a>Start by understanding the data that is available to you.</span>
<span id="cb51-158"><a href="#cb51-158"></a>If you have a codebook, you have struck gold!</span>
<span id="cb51-159"><a href="#cb51-159"></a>If not (the more common case), you'll need to do some detective work that often involves talking to people.</span>
<span id="cb51-160"><a href="#cb51-160"></a></span>
<span id="cb51-161"><a href="#cb51-161"></a>At this stage, ask yourself: - Where does my data come from?</span>
<span id="cb51-162"><a href="#cb51-162"></a>How was it collected?</span>
<span id="cb51-163"><a href="#cb51-163"></a><span class="ss">- </span>Is there a codebook?</span>
<span id="cb51-164"><a href="#cb51-164"></a>If not, how can I learn more about it?</span>
<span id="cb51-165"><a href="#cb51-165"></a><span class="ss">- </span>Are there people I can reach out to who have experience with this data?</span>
<span id="cb51-166"><a href="#cb51-166"></a></span>
<span id="cb51-167"><a href="#cb51-167"></a><span class="fu">## 14.3 Exercises</span></span>
<span id="cb51-168"><a href="#cb51-168"></a></span>
<span id="cb51-169"><a href="#cb51-169"></a>Suppose our goal is to work with data on movie reviews, and that we've already gone through the work to find a dataset.</span>
<span id="cb51-170"><a href="#cb51-170"></a>The imdb_5000_messy.csv file is posted on Moodle.</span>
<span id="cb51-171"><a href="#cb51-171"></a>Let's work with it!</span>
<span id="cb51-172"><a href="#cb51-172"></a></span>
<span id="cb51-173"><a href="#cb51-173"></a><span class="fu">### Exercise 1: Save Data Locally</span></span>
<span id="cb51-174"><a href="#cb51-174"></a></span>
<span id="cb51-175"><a href="#cb51-175"></a><span class="fu">#### Part a</span></span>
<span id="cb51-176"><a href="#cb51-176"></a></span>
<span id="cb51-177"><a href="#cb51-177"></a>On your laptop: - Download the "imdb_5000_messy.csv" file from Moodle - Move it to the data folder in your portfolio repository</span>
<span id="cb51-178"><a href="#cb51-178"></a></span>
<span id="cb51-179"><a href="#cb51-179"></a><span class="fu">#### Part b</span></span>
<span id="cb51-180"><a href="#cb51-180"></a></span>
<span id="cb51-181"><a href="#cb51-181"></a>Hot tip: After saving your data file, it's important to record appropriate citations and info in either a new qmd (eg: "imdb_5000_messy_README.qmd") or in the qmd where you'll analyze the data.</span>
<span id="cb51-182"><a href="#cb51-182"></a>These citations should include:</span>
<span id="cb51-183"><a href="#cb51-183"></a></span>
<span id="cb51-184"><a href="#cb51-184"></a><span class="ss">-   </span>the data source, i.e. where you found the data</span>
<span id="cb51-185"><a href="#cb51-185"></a><span class="ss">-   </span>the data creator, i.e. who / what group collected the original data</span>
<span id="cb51-186"><a href="#cb51-186"></a><span class="ss">-   </span>possibly a data codebook, i.e. descriptions of the data variables</span>
<span id="cb51-187"><a href="#cb51-187"></a></span>
<span id="cb51-188"><a href="#cb51-188"></a>To this end, check out where we originally got our IMDB data: <span class="ot">&lt;https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata&gt;</span></span>
<span id="cb51-189"><a href="#cb51-189"></a></span>
<span id="cb51-190"><a href="#cb51-190"></a>After visiting that website, take some quick notes here on the data source and creator:</span>
<span id="cb51-191"><a href="#cb51-191"></a></span>
<span id="cb51-192"><a href="#cb51-192"></a>*The data comes from Kaggle, a platform for data science competitions and datasets. The dataset was created by TMDB (The Movie Database), which is a community-built movie and TV database. The dataset contains information about 5,000 movies from IMDB, including details about cast, directors, ratings, revenue, and Facebook likes for various individuals involved in the films.*</span>
<span id="cb51-193"><a href="#cb51-193"></a></span>
<span id="cb51-194"><a href="#cb51-194"></a><span class="fu">### Exercise 2: Import Data to RStudio</span></span>
<span id="cb51-195"><a href="#cb51-195"></a></span>
<span id="cb51-196"><a href="#cb51-196"></a>Now that we have a local copy of our data file, let's get it into RStudio!</span>
<span id="cb51-197"><a href="#cb51-197"></a>Remember that this process depends on 2 things: the file type and location.</span>
<span id="cb51-198"><a href="#cb51-198"></a>Since our file type is a csv, we can import it using read_csv().</span>
<span id="cb51-199"><a href="#cb51-199"></a>But we have to supply the file location through a file path.</span>
<span id="cb51-200"><a href="#cb51-200"></a>To this end, we can either use an absolute file path or a relative file path.</span>
<span id="cb51-201"><a href="#cb51-201"></a></span>
<span id="cb51-202"><a href="#cb51-202"></a><span class="fu">#### Part a</span></span>
<span id="cb51-203"><a href="#cb51-203"></a></span>
<span id="cb51-204"><a href="#cb51-204"></a>An absolute file path describes the location of a file starting from the root or home directory.</span>
<span id="cb51-205"><a href="#cb51-205"></a>How we refer to the user root directory depends upon your machine:</span>
<span id="cb51-206"><a href="#cb51-206"></a></span>
<span id="cb51-207"><a href="#cb51-207"></a><span class="ss">-   </span>On a Mac: \~</span>
<span id="cb51-208"><a href="#cb51-208"></a><span class="ss">-   </span>On Windows: typically C:\</span>
<span id="cb51-209"><a href="#cb51-209"></a></span>
<span id="cb51-210"><a href="#cb51-210"></a>Then the complete file path to the IMDB data file in the data folder, depending on your machine an where you created your portfolio project, can be:</span>
<span id="cb51-211"><a href="#cb51-211"></a></span>
<span id="cb51-212"><a href="#cb51-212"></a><span class="ss">-   </span>On a Mac: \~/Desktop/portfolio/data/imdb_5000_messy.csv</span>
<span id="cb51-213"><a href="#cb51-213"></a><span class="ss">-   </span>On Windows: C:\Desktop\portfolio\data\imdb<span class="sc">\_</span>5000_messy.csv or C:<span class="sc">\\</span>Desktop<span class="sc">\\</span>portfolio<span class="sc">\\</span>data<span class="sc">\\</span>imdb_5000_messy.csv</span>
<span id="cb51-214"><a href="#cb51-214"></a></span>
<span id="cb51-215"><a href="#cb51-215"></a>Putting this together, use read_csv() with the appropriate absolute file path to import your data into RStudio.</span>
<span id="cb51-216"><a href="#cb51-216"></a>Save this as imdb_messy.</span>
<span id="cb51-217"><a href="#cb51-217"></a></span>
<span id="cb51-220"><a href="#cb51-220"></a><span class="in">```{r}</span></span>
<span id="cb51-221"><a href="#cb51-221"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb51-222"><a href="#cb51-222"></a><span class="co"># Using a placeholder path - you will need to use your actual path</span></span>
<span id="cb51-223"><a href="#cb51-223"></a><span class="co"># imdb_messy &lt;- read_csv("~/Desktop/portfolio/data/imdb_5000_messy.csv")</span></span>
<span id="cb51-224"><a href="#cb51-224"></a></span>
<span id="cb51-225"><a href="#cb51-225"></a><span class="co"># For this activity, let's load from an online source so the code runs for everyone</span></span>
<span id="cb51-226"><a href="#cb51-226"></a>imdb_messy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://mac-stat.github.io/data/imdb_5000_messy.csv"</span>)</span>
<span id="cb51-227"><a href="#cb51-227"></a></span>
<span id="cb51-228"><a href="#cb51-228"></a><span class="co"># Look at the first few rows</span></span>
<span id="cb51-229"><a href="#cb51-229"></a><span class="fu">head</span>(imdb_messy, <span class="dv">3</span>)</span>
<span id="cb51-230"><a href="#cb51-230"></a><span class="in">```</span></span>
<span id="cb51-231"><a href="#cb51-231"></a></span>
<span id="cb51-232"><a href="#cb51-232"></a><span class="fu">#### Part b</span></span>
<span id="cb51-233"><a href="#cb51-233"></a></span>
<span id="cb51-234"><a href="#cb51-234"></a>Absolute file paths can get really long, depending upon our number of sub-folders, and they should not be used when sharing code with other and instead relative file paths should be used.</span>
<span id="cb51-235"><a href="#cb51-235"></a>A relative file path describes the location of a file from the current "working directory", i.e. where RStudio would currently look for on your computer.</span>
<span id="cb51-236"><a href="#cb51-236"></a>Check what your working directory is inside this qmd:</span>
<span id="cb51-237"><a href="#cb51-237"></a></span>
<span id="cb51-240"><a href="#cb51-240"></a><span class="in">```{r}</span></span>
<span id="cb51-241"><a href="#cb51-241"></a><span class="co"># This should be the folder where you stored this qmd!</span></span>
<span id="cb51-242"><a href="#cb51-242"></a><span class="fu">getwd</span>()</span>
<span id="cb51-243"><a href="#cb51-243"></a><span class="in">```</span></span>
<span id="cb51-244"><a href="#cb51-244"></a></span>
<span id="cb51-245"><a href="#cb51-245"></a>Next, check what the working directory is for the console by typing getwd() in the console.</span>
<span id="cb51-246"><a href="#cb51-246"></a>This is probably different, meaning that the relative file paths that will work in your qmd won't work in the console!</span>
<span id="cb51-247"><a href="#cb51-247"></a>You can either exclusively work inside your qmd, or change the working directory in your console, by navigating to the following in the upper toolbar: Session <span class="sc">\&gt;</span> Set Working Directory <span class="sc">\&gt;</span> To Source File location.</span>
<span id="cb51-248"><a href="#cb51-248"></a></span>
<span id="cb51-249"><a href="#cb51-249"></a><span class="fu">#### Part c</span></span>
<span id="cb51-250"><a href="#cb51-250"></a></span>
<span id="cb51-251"><a href="#cb51-251"></a>As a good practice, we created a data folder and saved our data file (imdb_5000_messy.csv) into.</span>
<span id="cb51-252"><a href="#cb51-252"></a></span>
<span id="cb51-253"><a href="#cb51-253"></a>Since our .qmd analysis and .csv data live in the same project, we don't have to write out absolute file paths that go all the way to the root directory.</span>
<span id="cb51-254"><a href="#cb51-254"></a>We can use relative file paths that start from where our code file exists to where the data file exist:</span>
<span id="cb51-255"><a href="#cb51-255"></a></span>
<span id="cb51-256"><a href="#cb51-256"></a><span class="ss">-   </span>On a Mac: ../data/imdb_5000_messy.csv</span>
<span id="cb51-257"><a href="#cb51-257"></a><span class="ss">-   </span>On Windows: ..\data\imdb<span class="sc">\_</span>5000_messy.csv or ..<span class="sc">\\</span>data<span class="sc">\\</span>imdb_5000_messy.csv</span>
<span id="cb51-258"><a href="#cb51-258"></a></span>
<span id="cb51-259"><a href="#cb51-259"></a>NOTE: ..</span>
<span id="cb51-260"><a href="#cb51-260"></a>means go up one level in the file hierarchy, ie, go to the parent folder/directory.</span>
<span id="cb51-261"><a href="#cb51-261"></a></span>
<span id="cb51-262"><a href="#cb51-262"></a>Putting this together, use read_csv() with the appropriate relative file path to import your data into RStudio.</span>
<span id="cb51-263"><a href="#cb51-263"></a>Save this as imdb_temp (temp for "temporary").</span>
<span id="cb51-264"><a href="#cb51-264"></a>Convince yourself that this worked, i.e. you get the same dataset as imdb_messy.</span>
<span id="cb51-265"><a href="#cb51-265"></a></span>
<span id="cb51-268"><a href="#cb51-268"></a><span class="in">```{r}</span></span>
<span id="cb51-269"><a href="#cb51-269"></a><span class="co"># Using a relative path</span></span>
<span id="cb51-270"><a href="#cb51-270"></a><span class="co"># imdb_temp &lt;- read_csv("../data/imdb_5000_messy.csv")</span></span>
<span id="cb51-271"><a href="#cb51-271"></a></span>
<span id="cb51-272"><a href="#cb51-272"></a><span class="co"># For this activity, we'll just reuse the data loaded above</span></span>
<span id="cb51-273"><a href="#cb51-273"></a>imdb_temp <span class="ot">&lt;-</span> imdb_messy</span>
<span id="cb51-274"><a href="#cb51-274"></a></span>
<span id="cb51-275"><a href="#cb51-275"></a><span class="co"># Check they're the same by comparing dimensions</span></span>
<span id="cb51-276"><a href="#cb51-276"></a><span class="fu">dim</span>(imdb_messy) <span class="sc">==</span> <span class="fu">dim</span>(imdb_temp)</span>
<span id="cb51-277"><a href="#cb51-277"></a><span class="in">```</span></span>
<span id="cb51-278"><a href="#cb51-278"></a></span>
<span id="cb51-279"><a href="#cb51-279"></a><span class="fu">#### File Paths</span></span>
<span id="cb51-280"><a href="#cb51-280"></a></span>
<span id="cb51-281"><a href="#cb51-281"></a>Absolute file paths should be used when referring to files hosed on the web, eg, https://mac-stat.github.io/data/kiva_partners2.csv.</span>
<span id="cb51-282"><a href="#cb51-282"></a>In all other instances, relative file paths should be used.</span>
<span id="cb51-283"><a href="#cb51-283"></a></span>
<span id="cb51-284"><a href="#cb51-284"></a><span class="fu">#### Part d: OPTIONAL</span></span>
<span id="cb51-285"><a href="#cb51-285"></a></span>
<span id="cb51-286"><a href="#cb51-286"></a>Sometimes, we don't want to import the entire dataset.</span>
<span id="cb51-287"><a href="#cb51-287"></a>For example, we might want to...</span>
<span id="cb51-288"><a href="#cb51-288"></a><span class="ss">- </span>skips some rows, eg, if they're just "filler" - only import the first "n" rows, eg, if the dataset is really large - only import a random subset of "n" rows, eg, if the dataset is really large</span>
<span id="cb51-289"><a href="#cb51-289"></a></span>
<span id="cb51-290"><a href="#cb51-290"></a>The "data import cheat sheet" at the top of this qmd, or Google, are handy resources here.</span>
<span id="cb51-291"><a href="#cb51-291"></a>As one example...</span>
<span id="cb51-292"><a href="#cb51-292"></a></span>
<span id="cb51-295"><a href="#cb51-295"></a><span class="in">```{r}</span></span>
<span id="cb51-296"><a href="#cb51-296"></a><span class="co"># Try importing only the first 5 rows</span></span>
<span id="cb51-297"><a href="#cb51-297"></a>sample_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://mac-stat.github.io/data/imdb_5000_messy.csv"</span>, <span class="at">n_max =</span> <span class="dv">5</span>)</span>
<span id="cb51-298"><a href="#cb51-298"></a><span class="fu">nrow</span>(sample_data)</span>
<span id="cb51-299"><a href="#cb51-299"></a><span class="in">```</span></span>
<span id="cb51-300"><a href="#cb51-300"></a></span>
<span id="cb51-301"><a href="#cb51-301"></a><span class="fu">### Exercise 3: Check Data</span></span>
<span id="cb51-302"><a href="#cb51-302"></a></span>
<span id="cb51-303"><a href="#cb51-303"></a>After importing new data into RStudio, you MUST do some quick checks of the data.</span>
<span id="cb51-304"><a href="#cb51-304"></a>Here are two first steps that are especially useful.</span>
<span id="cb51-305"><a href="#cb51-305"></a></span>
<span id="cb51-306"><a href="#cb51-306"></a><span class="fu">#### Part a</span></span>
<span id="cb51-307"><a href="#cb51-307"></a></span>
<span id="cb51-308"><a href="#cb51-308"></a>Open imdb_messy in the spreadsheet-like viewer by typing View(imdb_messy) in the console.</span>
<span id="cb51-309"><a href="#cb51-309"></a>Sort this "spreadsheet" by different variables by clicking on the arrows next to the variable names.</span>
<span id="cb51-310"><a href="#cb51-310"></a>Do you notice anything unexpected?</span>
<span id="cb51-311"><a href="#cb51-311"></a></span>
<span id="cb51-312"><a href="#cb51-312"></a>*When sorting and examining the data in View, I noticed several issues:* *- The color variable has inconsistent values (B&amp;W, Black and White, color, Color, COLOR)* *- There are many missing values (NA) across different columns* *- Some values seem unrealistic or like data entry errors (e.g., extremely high budget numbers)*</span>
<span id="cb51-313"><a href="#cb51-313"></a></span>
<span id="cb51-314"><a href="#cb51-314"></a><span class="fu">#### Part b</span></span>
<span id="cb51-315"><a href="#cb51-315"></a></span>
<span id="cb51-316"><a href="#cb51-316"></a>Do a quick summary() of each variable in the dataset.</span>
<span id="cb51-317"><a href="#cb51-317"></a>One way to do this is below:</span>
<span id="cb51-318"><a href="#cb51-318"></a></span>
<span id="cb51-321"><a href="#cb51-321"></a><span class="in">```{r}</span></span>
<span id="cb51-322"><a href="#cb51-322"></a>imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb51-323"><a href="#cb51-323"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), as.factor)) <span class="sc">|&gt;</span>  <span class="co"># convert characters to factors in order to summarize</span></span>
<span id="cb51-324"><a href="#cb51-324"></a>  <span class="fu">summary</span>()</span>
<span id="cb51-325"><a href="#cb51-325"></a><span class="in">```</span></span>
<span id="cb51-326"><a href="#cb51-326"></a></span>
<span id="cb51-327"><a href="#cb51-327"></a>Follow-up: - What type of info is provided on quantitative variables?</span>
<span id="cb51-328"><a href="#cb51-328"></a>*For quantitative variables, the summary provides the minimum, 1st quartile, median, mean, 3rd quartile, and maximum values, along with the count of NA values.*</span>
<span id="cb51-329"><a href="#cb51-329"></a></span>
<span id="cb51-330"><a href="#cb51-330"></a><span class="ss">-   </span>What type of info is provided on categorical variables?</span>
<span id="cb51-331"><a href="#cb51-331"></a>    *For categorical variables (factors), the summary shows the frequency counts for each category and the number of NA values.*</span>
<span id="cb51-332"><a href="#cb51-332"></a></span>
<span id="cb51-333"><a href="#cb51-333"></a><span class="ss">-   </span>What stands out to you in these summaries?</span>
<span id="cb51-334"><a href="#cb51-334"></a>    Is there anything you'd need to clean before using this data?</span>
<span id="cb51-335"><a href="#cb51-335"></a>    *Several issues stand out:* *1. The color variable has inconsistent categories* *2. There are many NA values in multiple columns (e.g., gross, budget, plot_keywords)* *3. Some variables have very skewed distributions (e.g., Facebook likes)* *4. There are some unusual values (like the maximum budget of 1.22e+10)*</span>
<span id="cb51-336"><a href="#cb51-336"></a></span>
<span id="cb51-337"><a href="#cb51-337"></a><span class="fu">### Exercise 4: Clean Data: Factor Variables 1</span></span>
<span id="cb51-338"><a href="#cb51-338"></a></span>
<span id="cb51-339"><a href="#cb51-339"></a>If you didn't already in Exercise 3, check out the color variable in the imdb_messy dataset.</span>
<span id="cb51-340"><a href="#cb51-340"></a></span>
<span id="cb51-343"><a href="#cb51-343"></a><span class="in">```{r}</span></span>
<span id="cb51-344"><a href="#cb51-344"></a><span class="co"># Let's see all the unique values in the color variable</span></span>
<span id="cb51-345"><a href="#cb51-345"></a>imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb51-346"><a href="#cb51-346"></a>  <span class="fu">count</span>(color)</span>
<span id="cb51-347"><a href="#cb51-347"></a><span class="in">```</span></span>
<span id="cb51-348"><a href="#cb51-348"></a></span>
<span id="cb51-349"><a href="#cb51-349"></a>What's goofy about this / what do we need to fix?</span>
<span id="cb51-350"><a href="#cb51-350"></a>*The color variable has inconsistent values that essentially represent the same categories:* *- "B&amp;W" and "Black and White" both represent black and white films* *- "COLOR", "Color", and "color" all represent color films* *- There are also 19 NA values*</span>
<span id="cb51-351"><a href="#cb51-351"></a></span>
<span id="cb51-352"><a href="#cb51-352"></a>More specifically, what different categories does the color variable take, and how many movies fall into each of these categories?</span>
<span id="cb51-353"><a href="#cb51-353"></a>*As shown in the count above:* *- B&amp;W: 10 movies* *- Black and White: 199 movies* *- COLOR: 30 movies* *- Color: 4755 movies* *- color: 30 movies* *- NA: 19 movies*</span>
<span id="cb51-354"><a href="#cb51-354"></a></span>
<span id="cb51-355"><a href="#cb51-355"></a><span class="fu">### Exercise 5: Clean Data: Factor Variables 2</span></span>
<span id="cb51-356"><a href="#cb51-356"></a></span>
<span id="cb51-357"><a href="#cb51-357"></a>When working with categorical variables like color, the categories must be "clean", i.e. consistent and in the correct format.</span>
<span id="cb51-358"><a href="#cb51-358"></a>Let's make that happen.</span>
<span id="cb51-359"><a href="#cb51-359"></a></span>
<span id="cb51-360"><a href="#cb51-360"></a><span class="fu">#### Part a</span></span>
<span id="cb51-361"><a href="#cb51-361"></a></span>
<span id="cb51-362"><a href="#cb51-362"></a>We could open the .csv file in, say, Excel or Google sheets, clean up the color variable, save a clean copy, and then reimport that into RStudio.</span>
<span id="cb51-363"><a href="#cb51-363"></a>BUT that would be the wrong thing to do.</span>
<span id="cb51-364"><a href="#cb51-364"></a>Why is it important to use R code, which we then save inside this qmd, to clean our data?</span>
<span id="cb51-365"><a href="#cb51-365"></a></span>
<span id="cb51-366"><a href="#cb51-366"></a>*It's important to use R code to clean data for several reasons:* *1. Reproducibility - The entire data cleaning process is documented and can be rerun* *2. Transparency - Others can see exactly what changes were made* *3. Consistency - The same process will be applied every time* *4. Efficiency - If the raw data changes, we can easily rerun our cleaning code* *5. Version control - Changes to our cleaning process can be tracked*</span>
<span id="cb51-367"><a href="#cb51-367"></a></span>
<span id="cb51-368"><a href="#cb51-368"></a><span class="fu">#### Part b</span></span>
<span id="cb51-369"><a href="#cb51-369"></a></span>
<span id="cb51-370"><a href="#cb51-370"></a>Let's use R code to change the color variable so that it appropriately combines the various categories into only 2: Color and Black_White.</span>
<span id="cb51-371"><a href="#cb51-371"></a>We've learned a couple sets of string-related tools that could be handy here.</span>
<span id="cb51-372"><a href="#cb51-372"></a>First, starting with the imdb_messy data, change the color variable using one of the functions we learned in the Factors lesson.</span>
<span id="cb51-373"><a href="#cb51-373"></a></span>
<span id="cb51-376"><a href="#cb51-376"></a><span class="in">```{r}</span></span>
<span id="cb51-377"><a href="#cb51-377"></a><span class="co"># Using fct_recode to recode the color variable</span></span>
<span id="cb51-378"><a href="#cb51-378"></a>imdb_temp <span class="ot">&lt;-</span> imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb51-379"><a href="#cb51-379"></a>  <span class="fu">mutate</span>(<span class="at">color =</span> <span class="fu">fct_recode</span>(color,</span>
<span id="cb51-380"><a href="#cb51-380"></a>                          <span class="st">"Color"</span> <span class="ot">=</span> <span class="st">"COLOR"</span>,</span>
<span id="cb51-381"><a href="#cb51-381"></a>                          <span class="st">"Color"</span> <span class="ot">=</span> <span class="st">"color"</span>,</span>
<span id="cb51-382"><a href="#cb51-382"></a>                          <span class="st">"Black_White"</span> <span class="ot">=</span> <span class="st">"B&amp;W"</span>,</span>
<span id="cb51-383"><a href="#cb51-383"></a>                          <span class="st">"Black_White"</span> <span class="ot">=</span> <span class="st">"Black and White"</span>))</span>
<span id="cb51-384"><a href="#cb51-384"></a></span>
<span id="cb51-385"><a href="#cb51-385"></a><span class="co"># Check the result</span></span>
<span id="cb51-386"><a href="#cb51-386"></a>imdb_temp <span class="sc">|&gt;</span></span>
<span id="cb51-387"><a href="#cb51-387"></a>  <span class="fu">count</span>(color)</span>
<span id="cb51-388"><a href="#cb51-388"></a><span class="in">```</span></span>
<span id="cb51-389"><a href="#cb51-389"></a></span>
<span id="cb51-390"><a href="#cb51-390"></a><span class="fu">#### Part c</span></span>
<span id="cb51-391"><a href="#cb51-391"></a></span>
<span id="cb51-392"><a href="#cb51-392"></a>Repeat Part b using one of our string functions from the String lesson:</span>
<span id="cb51-393"><a href="#cb51-393"></a></span>
<span id="cb51-396"><a href="#cb51-396"></a><span class="in">```{r}</span></span>
<span id="cb51-397"><a href="#cb51-397"></a><span class="co"># Using str_replace to clean the color variable</span></span>
<span id="cb51-398"><a href="#cb51-398"></a>imdb_temp2 <span class="ot">&lt;-</span> imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb51-399"><a href="#cb51-399"></a>  <span class="fu">mutate</span>(<span class="at">color =</span> <span class="fu">str_replace</span>(color, <span class="st">"COLOR"</span>, <span class="st">"Color"</span>),</span>
<span id="cb51-400"><a href="#cb51-400"></a>         <span class="at">color =</span> <span class="fu">str_replace</span>(color, <span class="st">"color"</span>, <span class="st">"Color"</span>),</span>
<span id="cb51-401"><a href="#cb51-401"></a>         <span class="at">color =</span> <span class="fu">str_replace</span>(color, <span class="st">"B&amp;W"</span>, <span class="st">"Black_White"</span>),</span>
<span id="cb51-402"><a href="#cb51-402"></a>         <span class="at">color =</span> <span class="fu">str_replace</span>(color, <span class="st">"Black and White"</span>, <span class="st">"Black_White"</span>))</span>
<span id="cb51-403"><a href="#cb51-403"></a></span>
<span id="cb51-404"><a href="#cb51-404"></a><span class="co"># Check the result</span></span>
<span id="cb51-405"><a href="#cb51-405"></a>imdb_temp2 <span class="sc">|&gt;</span></span>
<span id="cb51-406"><a href="#cb51-406"></a>  <span class="fu">count</span>(color)</span>
<span id="cb51-407"><a href="#cb51-407"></a><span class="in">```</span></span>
<span id="cb51-408"><a href="#cb51-408"></a></span>
<span id="cb51-409"><a href="#cb51-409"></a><span class="fu">### Exercise 6: Clean Data: Missing Data 1</span></span>
<span id="cb51-410"><a href="#cb51-410"></a></span>
<span id="cb51-411"><a href="#cb51-411"></a>Throughout these exercises, you've probably noticed that there's a bunch of missing data.</span>
<span id="cb51-412"><a href="#cb51-412"></a>This is encoded as NA (not available) in R.</span>
<span id="cb51-413"><a href="#cb51-413"></a>There are a few questions to address about missing data:</span>
<span id="cb51-414"><a href="#cb51-414"></a></span>
<span id="cb51-415"><a href="#cb51-415"></a><span class="ss">1.  </span>How many values are missing data? What's the volume of the missingness?</span>
<span id="cb51-416"><a href="#cb51-416"></a><span class="ss">2.  </span>Why are some values missing?</span>
<span id="cb51-417"><a href="#cb51-417"></a><span class="ss">3.  </span>What should we do about the missing values?</span>
<span id="cb51-418"><a href="#cb51-418"></a></span>
<span id="cb51-419"><a href="#cb51-419"></a>Let's consider the first 2 questions in this exercise.</span>
<span id="cb51-420"><a href="#cb51-420"></a></span>
<span id="cb51-421"><a href="#cb51-421"></a><span class="fu">#### Part a</span></span>
<span id="cb51-422"><a href="#cb51-422"></a></span>
<span id="cb51-423"><a href="#cb51-423"></a>As a first step, let's simply understand the volume of NAs.</span>
<span id="cb51-424"><a href="#cb51-424"></a>Specifically:</span>
<span id="cb51-425"><a href="#cb51-425"></a></span>
<span id="cb51-428"><a href="#cb51-428"></a><span class="in">```{r}</span></span>
<span id="cb51-429"><a href="#cb51-429"></a><span class="co"># Count the total number of rows in imdb_messy</span></span>
<span id="cb51-430"><a href="#cb51-430"></a><span class="fu">nrow</span>(imdb_messy)</span>
<span id="cb51-431"><a href="#cb51-431"></a><span class="in">```</span></span>
<span id="cb51-432"><a href="#cb51-432"></a></span>
<span id="cb51-435"><a href="#cb51-435"></a><span class="in">```{r}</span></span>
<span id="cb51-436"><a href="#cb51-436"></a><span class="co"># Then count the number of NAs in each column</span></span>
<span id="cb51-437"><a href="#cb51-437"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(imdb_messy))</span>
<span id="cb51-438"><a href="#cb51-438"></a><span class="in">```</span></span>
<span id="cb51-439"><a href="#cb51-439"></a></span>
<span id="cb51-442"><a href="#cb51-442"></a><span class="in">```{r}</span></span>
<span id="cb51-443"><a href="#cb51-443"></a><span class="co"># Then count the number of NAs in a specific column</span></span>
<span id="cb51-444"><a href="#cb51-444"></a>imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb51-445"><a href="#cb51-445"></a>  <span class="fu">summarize</span>(<span class="at">na_count =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(actor_1_facebook_likes)))</span>
<span id="cb51-446"><a href="#cb51-446"></a><span class="in">```</span></span>
<span id="cb51-447"><a href="#cb51-447"></a></span>
<span id="cb51-448"><a href="#cb51-448"></a><span class="fu">#### Part b</span></span>
<span id="cb51-449"><a href="#cb51-449"></a></span>
<span id="cb51-450"><a href="#cb51-450"></a>As a second step, let's think about why some values are missing.</span>
<span id="cb51-451"><a href="#cb51-451"></a>Study the individual observations with NAs carefully.</span>
<span id="cb51-452"><a href="#cb51-452"></a>Why do you think they are missing?</span>
<span id="cb51-453"><a href="#cb51-453"></a>Are certain films more likely to have more NAs than others?</span>
<span id="cb51-454"><a href="#cb51-454"></a></span>
<span id="cb51-455"><a href="#cb51-455"></a>*After examining the data, it appears that:* *1. Older films tend to have more missing values, especially for Facebook-related data* *2. Some films may be missing budget or gross data because this information wasn't publicly available* *3. Some missing values (like in the actor columns) might be from documentaries or films without traditional actors* *4. Some films might be missing content ratings if they weren't officially rated*</span>
<span id="cb51-456"><a href="#cb51-456"></a></span>
<span id="cb51-457"><a href="#cb51-457"></a><span class="fu">#### Part c</span></span>
<span id="cb51-458"><a href="#cb51-458"></a></span>
<span id="cb51-459"><a href="#cb51-459"></a>Consider a more specific example.</span>
<span id="cb51-460"><a href="#cb51-460"></a>Obtain a dataset of movies that are missing data on actor_1_facebook_likes.</span>
<span id="cb51-461"><a href="#cb51-461"></a>Then explain why you think there are NAs.</span>
<span id="cb51-462"><a href="#cb51-462"></a></span>
<span id="cb51-465"><a href="#cb51-465"></a><span class="in">```{r}</span></span>
<span id="cb51-466"><a href="#cb51-466"></a><span class="co"># Get films with missing actor_1_facebook_likes</span></span>
<span id="cb51-467"><a href="#cb51-467"></a>films_missing_actor_likes <span class="ot">&lt;-</span> imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb51-468"><a href="#cb51-468"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(actor_1_facebook_likes))</span>
<span id="cb51-469"><a href="#cb51-469"></a></span>
<span id="cb51-470"><a href="#cb51-470"></a><span class="co"># Examine these films</span></span>
<span id="cb51-471"><a href="#cb51-471"></a>films_missing_actor_likes</span>
<span id="cb51-472"><a href="#cb51-472"></a><span class="in">```</span></span>
<span id="cb51-473"><a href="#cb51-473"></a></span>
<span id="cb51-474"><a href="#cb51-474"></a>*Looking at these films, it appears they are documentaries or similar non-fiction films that don't have traditional actors. Since there are no lead actors, there wouldn't be Facebook likes data for "actor_1". In these cases, NA makes sense because the field simply doesn't apply to these films rather than indicating missing information about an actor.*</span>
<span id="cb51-475"><a href="#cb51-475"></a></span>
<span id="cb51-476"><a href="#cb51-476"></a><span class="fu">### Exercise 7: Clean Data: Missing Data 2</span></span>
<span id="cb51-477"><a href="#cb51-477"></a></span>
<span id="cb51-478"><a href="#cb51-478"></a>Next, let's think about what to do about the missing values.</span>
<span id="cb51-479"><a href="#cb51-479"></a>There is no perfect or universal approach here.</span>
<span id="cb51-480"><a href="#cb51-480"></a>Rather, we must think carefully about...</span>
<span id="cb51-481"><a href="#cb51-481"></a></span>
<span id="cb51-482"><a href="#cb51-482"></a><span class="ss">1.  </span>Why the values are missing?</span>
<span id="cb51-483"><a href="#cb51-483"></a><span class="ss">2.  </span>What we want to do with our data?</span>
<span id="cb51-484"><a href="#cb51-484"></a><span class="ss">3.  </span>What is the impact of removing or replacing missing data on our work / conclusions?</span>
<span id="cb51-485"><a href="#cb51-485"></a></span>
<span id="cb51-486"><a href="#cb51-486"></a><span class="fu">#### Part a</span></span>
<span id="cb51-487"><a href="#cb51-487"></a></span>
<span id="cb51-488"><a href="#cb51-488"></a>Calculate the average duration of a film.</span>
<span id="cb51-489"><a href="#cb51-489"></a>THINK: How can we deal with the NA's?</span>
<span id="cb51-490"><a href="#cb51-490"></a></span>
<span id="cb51-493"><a href="#cb51-493"></a><span class="in">```{r}</span></span>
<span id="cb51-494"><a href="#cb51-494"></a><span class="co"># Calculate average duration, ignoring NA values</span></span>
<span id="cb51-495"><a href="#cb51-495"></a>imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb51-496"><a href="#cb51-496"></a>  <span class="fu">summarize</span>(<span class="at">avg_duration =</span> <span class="fu">mean</span>(duration, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb51-497"><a href="#cb51-497"></a><span class="in">```</span></span>
<span id="cb51-498"><a href="#cb51-498"></a></span>
<span id="cb51-499"><a href="#cb51-499"></a>Follow-up: - How are the NAs dealt with here?</span>
<span id="cb51-500"><a href="#cb51-500"></a>Did we have to create and save a new dataset in order to do this analysis?</span>
<span id="cb51-501"><a href="#cb51-501"></a></span>
<span id="cb51-502"><a href="#cb51-502"></a>*The NAs are handled using the na.rm = TRUE parameter in the mean() function, which tells R to ignore NA values when calculating the mean. We did not need to create a new dataset for this analysis - we simply addressed the NAs within the calculation itself. This approach is convenient for one-off calculations but doesn't permanently affect the dataset.*</span>
<span id="cb51-503"><a href="#cb51-503"></a></span>
<span id="cb51-504"><a href="#cb51-504"></a><span class="fu">#### Part b</span></span>
<span id="cb51-505"><a href="#cb51-505"></a></span>
<span id="cb51-506"><a href="#cb51-506"></a>Try out the drop_na() function:</span>
<span id="cb51-507"><a href="#cb51-507"></a></span>
<span id="cb51-510"><a href="#cb51-510"></a><span class="in">```{r}</span></span>
<span id="cb51-511"><a href="#cb51-511"></a><span class="co"># Remove all rows with any NA values</span></span>
<span id="cb51-512"><a href="#cb51-512"></a>imdb_complete <span class="ot">&lt;-</span> <span class="fu">drop_na</span>(imdb_messy)</span>
<span id="cb51-513"><a href="#cb51-513"></a></span>
<span id="cb51-514"><a href="#cb51-514"></a><span class="co"># Check how many rows remain</span></span>
<span id="cb51-515"><a href="#cb51-515"></a><span class="fu">nrow</span>(imdb_complete)</span>
<span id="cb51-516"><a href="#cb51-516"></a><span class="in">```</span></span>
<span id="cb51-517"><a href="#cb51-517"></a></span>
<span id="cb51-518"><a href="#cb51-518"></a>Follow-up questions: - What did drop_na() do?</span>
<span id="cb51-519"><a href="#cb51-519"></a>How many data points are left?</span>
<span id="cb51-520"><a href="#cb51-520"></a>*The drop_na() function removed all rows that contained at least one NA value in any column. We started with 5,043 rows and ended with only 3,756 rows - meaning we lost 1,287 rows (about 25.5% of our data).*</span>
<span id="cb51-521"><a href="#cb51-521"></a></span>
<span id="cb51-522"><a href="#cb51-522"></a><span class="ss">-   </span>In what situations might this function be a good idea?</span>
<span id="cb51-523"><a href="#cb51-523"></a>    *This function might be a good idea when:* *- You need complete cases for certain statistical methods that can't handle NAs* *- The amount of missing data is small, so you don't lose much information* *- The missing data is missing completely at random (MCAR) so removing rows won't introduce bias* *- You need a quick, clean dataset for a simple analysis or visualization*</span>
<span id="cb51-524"><a href="#cb51-524"></a></span>
<span id="cb51-525"><a href="#cb51-525"></a><span class="ss">-   </span>In what situations might this function be a bad idea?</span>
<span id="cb51-526"><a href="#cb51-526"></a>    *This function might be a bad idea when:* *- You lose too much data (as in this case - losing 25% is substantial)* *- The missing data follows a pattern, so removing rows could introduce bias* *- The NAs actually represent meaningful information (like in our actor_1_facebook_likes example)* *- You only need a few variables for your analysis, but you're removing rows based on NAs in variables you don't need*</span>
<span id="cb51-527"><a href="#cb51-527"></a></span>
<span id="cb51-528"><a href="#cb51-528"></a><span class="fu">#### Part c</span></span>
<span id="cb51-529"><a href="#cb51-529"></a></span>
<span id="cb51-530"><a href="#cb51-530"></a>drop_na() removes data points that have any NA values, even if we don't care about the variable(s) for which data is missing.</span>
<span id="cb51-531"><a href="#cb51-531"></a>This can result in losing a lot of data points that do have data on the variables we actually care about!</span>
<span id="cb51-532"><a href="#cb51-532"></a>For example, suppose we only want to explore the relationship between film duration and whether it's in color.</span>
<span id="cb51-533"><a href="#cb51-533"></a>Check out a plot:</span>
<span id="cb51-534"><a href="#cb51-534"></a></span>
<span id="cb51-537"><a href="#cb51-537"></a><span class="in">```{r}</span></span>
<span id="cb51-538"><a href="#cb51-538"></a><span class="co"># Try to plot with the full dataset</span></span>
<span id="cb51-539"><a href="#cb51-539"></a><span class="fu">ggplot</span>(imdb_messy, <span class="fu">aes</span>(<span class="at">x =</span> duration, <span class="at">fill =</span> color)) <span class="sc">+</span></span>
<span id="cb51-540"><a href="#cb51-540"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb51-541"><a href="#cb51-541"></a><span class="in">```</span></span>
<span id="cb51-542"><a href="#cb51-542"></a></span>
<span id="cb51-543"><a href="#cb51-543"></a>Follow-up: - Create a new dataset with only and all movies that have complete info on duration and color.</span>
<span id="cb51-544"><a href="#cb51-544"></a>HINT: You could use !i</span>
<span id="cb51-545"><a href="#cb51-545"></a>s.na(<span class="sc">\_\_\_</span>) or drop_na() (differently than above)</span>
<span id="cb51-546"><a href="#cb51-546"></a></span>
<span id="cb51-549"><a href="#cb51-549"></a><span class="in">```{r}</span></span>
<span id="cb51-550"><a href="#cb51-550"></a><span class="co"># Create dataset with only movies that have complete info on duration and color</span></span>
<span id="cb51-551"><a href="#cb51-551"></a>imdb_duration_color <span class="ot">&lt;-</span> imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb51-552"><a href="#cb51-552"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(duration), <span class="sc">!</span><span class="fu">is.na</span>(color))</span>
<span id="cb51-553"><a href="#cb51-553"></a></span>
<span id="cb51-554"><a href="#cb51-554"></a><span class="co"># Check how many rows remain</span></span>
<span id="cb51-555"><a href="#cb51-555"></a><span class="fu">nrow</span>(imdb_duration_color)</span>
<span id="cb51-556"><a href="#cb51-556"></a><span class="in">```</span></span>
<span id="cb51-557"><a href="#cb51-557"></a></span>
<span id="cb51-558"><a href="#cb51-558"></a><span class="ss">-   </span>Use this new dataset to create a new and improved plot.</span>
<span id="cb51-559"><a href="#cb51-559"></a></span>
<span id="cb51-562"><a href="#cb51-562"></a><span class="in">```{r}</span></span>
<span id="cb51-563"><a href="#cb51-563"></a><span class="co"># Create improved plot</span></span>
<span id="cb51-564"><a href="#cb51-564"></a><span class="fu">ggplot</span>(imdb_duration_color, <span class="fu">aes</span>(<span class="at">x =</span> duration, <span class="at">fill =</span> color)) <span class="sc">+</span></span>
<span id="cb51-565"><a href="#cb51-565"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb51-566"><a href="#cb51-566"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Movie Duration by Color Type"</span>,</span>
<span id="cb51-567"><a href="#cb51-567"></a>       <span class="at">x =</span> <span class="st">"Duration (minutes)"</span>,</span>
<span id="cb51-568"><a href="#cb51-568"></a>       <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb51-569"><a href="#cb51-569"></a>       <span class="at">fill =</span> <span class="st">"Film Type"</span>)</span>
<span id="cb51-570"><a href="#cb51-570"></a><span class="in">```</span></span>
<span id="cb51-571"><a href="#cb51-571"></a></span>
<span id="cb51-572"><a href="#cb51-572"></a><span class="ss">-   </span>How many movies remain in your new dataset? Hence why this is better than using the dataset from part b?</span>
<span id="cb51-573"><a href="#cb51-573"></a></span>
<span id="cb51-574"><a href="#cb51-574"></a>*We have 5,010 movies in our new dataset, compared to just 3,756 in the completely clean dataset. This is much better because we're only removing movies that are missing the specific variables we need for our analysis (duration and color). We've kept 1,254 more movies that would have been unnecessarily removed if we had used drop_na() on the entire dataset.*</span>
<span id="cb51-575"><a href="#cb51-575"></a></span>
<span id="cb51-576"><a href="#cb51-576"></a><span class="fu">#### Part d</span></span>
<span id="cb51-577"><a href="#cb51-577"></a></span>
<span id="cb51-578"><a href="#cb51-578"></a>In some cases, missing data is more non-data than unknown data.</span>
<span id="cb51-579"><a href="#cb51-579"></a>For example, the films with NAs for actor_1_facebook_likes actually have 0 Facebook likes–they don't even have actors!</span>
<span id="cb51-580"><a href="#cb51-580"></a>In these cases, we can replace the NAs with a 0.</span>
<span id="cb51-581"><a href="#cb51-581"></a>Use the replace_na() function to create a new dataset (imdb_temp) that replaces the NAs in actor_1_facebook_likes with 0.</span>
<span id="cb51-582"><a href="#cb51-582"></a></span>
<span id="cb51-585"><a href="#cb51-585"></a><span class="in">```{r}</span></span>
<span id="cb51-586"><a href="#cb51-586"></a><span class="co"># Replace NAs in actor_1_facebook_likes with 0</span></span>
<span id="cb51-587"><a href="#cb51-587"></a>imdb_temp <span class="ot">&lt;-</span> imdb_messy <span class="sc">|&gt;</span></span>
<span id="cb51-588"><a href="#cb51-588"></a>  <span class="fu">mutate</span>(<span class="at">actor_1_facebook_likes =</span> <span class="fu">replace_na</span>(actor_1_facebook_likes, <span class="dv">0</span>))</span>
<span id="cb51-589"><a href="#cb51-589"></a></span>
<span id="cb51-590"><a href="#cb51-590"></a><span class="co"># Check if there are any NAs left in that column</span></span>
<span id="cb51-591"><a href="#cb51-591"></a>imdb_temp <span class="sc">|&gt;</span></span>
<span id="cb51-592"><a href="#cb51-592"></a>  <span class="fu">summarize</span>(<span class="at">na_count =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(actor_1_facebook_likes)))</span>
<span id="cb51-593"><a href="#cb51-593"></a><span class="in">```</span></span>
<span id="cb51-594"><a href="#cb51-594"></a></span>
<span id="cb51-595"><a href="#cb51-595"></a><span class="fu">### Exercise 8: New Data + Projects</span></span>
<span id="cb51-596"><a href="#cb51-596"></a></span>
<span id="cb51-597"><a href="#cb51-597"></a>Let's practice the above ideas while also planting some seeds for the course project.</span>
<span id="cb51-598"><a href="#cb51-598"></a>Each group will pick and analyze their own dataset.</span>
<span id="cb51-599"><a href="#cb51-599"></a>The people you're sitting with today aren't necessarily your project groups!</span>
<span id="cb51-600"><a href="#cb51-600"></a>BUT do some brainstorming together:</span>
<span id="cb51-601"><a href="#cb51-601"></a></span>
<span id="cb51-602"><a href="#cb51-602"></a><span class="ss">1.  </span>Share with each other: What are some personal hobbies or passions or things you've been thinking about or things you'd like to learn more about?</span>
<span id="cb51-603"><a href="#cb51-603"></a>    Don't think too hard about this!</span>
<span id="cb51-604"><a href="#cb51-604"></a>    Just share what's at the top of mind today.</span>
<span id="cb51-605"><a href="#cb51-605"></a></span>
<span id="cb51-606"><a href="#cb51-606"></a><span class="ss">2.  </span>Each individual: Find a dataset online that's related to one of the topics you shared in the above prompt.</span>
<span id="cb51-607"><a href="#cb51-607"></a></span>
<span id="cb51-608"><a href="#cb51-608"></a><span class="ss">3.  </span>Discuss what data you found with your group!</span>
<span id="cb51-609"><a href="#cb51-609"></a></span>
<span id="cb51-610"><a href="#cb51-610"></a><span class="ss">4.  </span>Load the data into RStudio, perform some basic checks, and perform some preliminary cleaning, as necessary.</span>
<span id="cb51-611"><a href="#cb51-611"></a></span>
<span id="cb51-612"><a href="#cb51-612"></a>*For this exercise, I found a dataset about global coffee production. Let me demonstrate how I would approach exploring this dataset:*</span>
<span id="cb51-613"><a href="#cb51-613"></a></span>
<span id="cb51-616"><a href="#cb51-616"></a><span class="in">```{r}</span></span>
<span id="cb51-617"><a href="#cb51-617"></a><span class="co"># Load a sample dataset - using mtcars which is built into R</span></span>
<span id="cb51-618"><a href="#cb51-618"></a><span class="co"># In a real scenario, you would load your own dataset</span></span>
<span id="cb51-619"><a href="#cb51-619"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb51-620"><a href="#cb51-620"></a></span>
<span id="cb51-621"><a href="#cb51-621"></a><span class="co"># Basic checks</span></span>
<span id="cb51-622"><a href="#cb51-622"></a><span class="fu">head</span>(mtcars)</span>
<span id="cb51-623"><a href="#cb51-623"></a><span class="in">```</span></span>
<span id="cb51-624"><a href="#cb51-624"></a></span>
<span id="cb51-627"><a href="#cb51-627"></a><span class="in">```{r}</span></span>
<span id="cb51-628"><a href="#cb51-628"></a><span class="co"># Check structure</span></span>
<span id="cb51-629"><a href="#cb51-629"></a><span class="fu">str</span>(mtcars)</span>
<span id="cb51-630"><a href="#cb51-630"></a><span class="in">```</span></span>
<span id="cb51-631"><a href="#cb51-631"></a></span>
<span id="cb51-634"><a href="#cb51-634"></a><span class="in">```{r}</span></span>
<span id="cb51-635"><a href="#cb51-635"></a><span class="co"># Check for missing values - mtcars doesn't have NAs, but this is how you'd check</span></span>
<span id="cb51-636"><a href="#cb51-636"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(mtcars))</span>
<span id="cb51-637"><a href="#cb51-637"></a><span class="in">```</span></span>
<span id="cb51-638"><a href="#cb51-638"></a></span>
<span id="cb51-641"><a href="#cb51-641"></a><span class="in">```{r}</span></span>
<span id="cb51-642"><a href="#cb51-642"></a><span class="co"># Basic cleaning demonstration - convert categorical variables to factors</span></span>
<span id="cb51-643"><a href="#cb51-643"></a>mtcars_clean <span class="ot">&lt;-</span> mtcars <span class="sc">|&gt;</span></span>
<span id="cb51-644"><a href="#cb51-644"></a>  <span class="fu">mutate</span>(</span>
<span id="cb51-645"><a href="#cb51-645"></a>    <span class="at">cyl =</span> <span class="fu">as.factor</span>(cyl),</span>
<span id="cb51-646"><a href="#cb51-646"></a>    <span class="at">vs =</span> <span class="fu">as.factor</span>(vs),</span>
<span id="cb51-647"><a href="#cb51-647"></a>    <span class="at">am =</span> <span class="fu">as.factor</span>(am),</span>
<span id="cb51-648"><a href="#cb51-648"></a>    <span class="at">gear =</span> <span class="fu">as.factor</span>(gear),</span>
<span id="cb51-649"><a href="#cb51-649"></a>    <span class="at">carb =</span> <span class="fu">as.factor</span>(carb)</span>
<span id="cb51-650"><a href="#cb51-650"></a>  )</span>
<span id="cb51-651"><a href="#cb51-651"></a></span>
<span id="cb51-652"><a href="#cb51-652"></a><span class="co"># Create quick visualization to explore the data</span></span>
<span id="cb51-653"><a href="#cb51-653"></a><span class="fu">ggplot</span>(mtcars_clean, <span class="fu">aes</span>(<span class="at">x =</span> wt, <span class="at">y =</span> mpg, <span class="at">color =</span> cyl)) <span class="sc">+</span></span>
<span id="cb51-654"><a href="#cb51-654"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb51-655"><a href="#cb51-655"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Car Weight vs. Fuel Efficiency by Cylinder Count"</span>,</span>
<span id="cb51-656"><a href="#cb51-656"></a>       <span class="at">x =</span> <span class="st">"Weight (1000 lbs)"</span>,</span>
<span id="cb51-657"><a href="#cb51-657"></a>       <span class="at">y =</span> <span class="st">"Miles Per Gallon"</span>,</span>
<span id="cb51-658"><a href="#cb51-658"></a>       <span class="at">color =</span> <span class="st">"Cylinders"</span>)</span>
<span id="cb51-659"><a href="#cb51-659"></a><span class="in">```</span></span>
<span id="cb51-660"><a href="#cb51-660"></a></span>
<span id="cb51-661"><a href="#cb51-661"></a>*This example shows the basic workflow: loading data, checking its structure, identifying missing values, cleaning as needed, and creating exploratory visualizations.*</span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>